import fs from 'node:fs';import crypto from 'node:crypto';
const RAW='FRESH_2026_MARKET_PANEL_RAW.json',GATE='FRESH_2026_MARKET_PANEL_GATE.json';
const raw=JSON.parse(fs.readFileSync(RAW,'utf8'));
const PRESETS={standard:{list:[['Pat Fitzmaurice',30],['Justin Boone',25],['Sean Koerner',20],['Andrew Erickson',15],['Derek Brown',10]],max:5},rb:{list:[['Pat Fitzmaurice',35],['Justin Boone',30],['Sean Koerner',20],['Andrew Erickson',15],['Derek Brown',10]],max:4},wr:{list:[['Matt Harmon',35],['Pat Fitzmaurice',30],['Justin Boone',20],['Andrew Erickson',15],['Derek Brown',10]],max:4},qb:{list:[['Pat Fitzmaurice',45],['Justin Boone',30],['Sean Koerner',25],['Andrew Erickson',15]],max:3},te:{list:[['Pat Fitzmaurice',40],['Justin Boone',25],['Andrew Erickson',20],['Derek Brown',15],['Sean Koerner',15]],max:4}};
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(jr|sr|ii|iii|iv)\.?\b/g,'').replace(/[^a-z0-9]+/g,'');}
function slug(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/['’]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');}
function dec(s){return String(s||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
async function fetchText(url){const r=await fetch(url,{headers:{accept:'text/html','user-agent':'Mozilla/5.0 (compatible; PITTI-Freeze-Augment/1.0)'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.text();}
function rows(html){return [...html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)].map(m=>[...m[1].matchAll(/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(x=>dec(x[1]))).filter(x=>x.length);}
function player(s){const t=String(s||'').trim(),m=t.toUpperCase().match(/\b(QB|RB|WR|TE|K|DST)\b/);if(!m)return null;const pos=m[1],name=t.replace(/\s+[A-Z]{2,3}\s*-\s*(QB|RB|WR|TE|K|DST)\b.*$/i,'').replace(/\s+(QB|RB|WR|TE|K|DST)\s*\d*\s*$/i,'').trim();return name?{name,pos}:null;}
function parseTarget(html,target){const rr=rows(html),needle=target.toLowerCase(),out=new Map();let tc=-1,pc=-1;for(const c of rr){const lc=c.map(x=>x.toLowerCase()),nt=lc.findIndex(x=>x.includes(needle)&&x.includes('rank')),np=lc.findIndex(x=>x==='player'||x.includes('player'));if(nt>=0&&np>=0){tc=nt;pc=np;continue;}if(tc<0||pc<0||c.length<=Math.max(tc,pc))continue;const rank=Number(String(c[tc]).match(/\d{1,3}/)?.[0]),p=player(c[pc]);if(Number.isFinite(rank)&&rank>0&&rank<=500&&p)out.set(norm(p.name),{rank,name:p.name,pos:p.pos,exact:true,spread:0,anchors:0});}return out;}
async function comparison(target,anchor){const a=slug(anchor),t=slug(target),urls=[`https://www.fantasypros.com/nfl/rankings/${a}-${t}.php?scoring=HALF&type=draft`,`https://www.fantasypros.com/nfl/rankings/${t}-${a}.php?scoring=HALF&type=draft`];for(const url of urls){try{const html=await fetchText(url),m=parseTarget(html,target);if(m.size>=10)return{url,map:m};}catch{}}return null;}
function median(a){const x=[...a].sort((a,b)=>a-b);return x.length%2?x[(x.length-1)/2]:(x[x.length/2-1]+x[x.length/2])/2;}
const anchorNames=['Pat Fitzmaurice','Andrew Erickson','Derek Brown'];
const pool=new Map((raw.pool_rows||[]).map(x=>[x.key,{key:x.key,name:x.name,pos:x.pos}]));
const anchorMaps=Object.fromEntries(anchorNames.map(n=>[n,new Map()]));
for(const [k,r] of Object.entries(raw.panels?.standard||{})){for(const v of r.individual||[]){if(anchorMaps[v.expertName])anchorMaps[v.expertName].set(k,{rank:Number(v.rank),posRank:Number.isFinite(Number(v.posRank))?Number(v.posRank):null,name:r.name,pos:r.pos,exact:true,spread:0,anchors:0});}}
async function reconstruct(target){const exact=new Map(),used=[];for(const a of anchorNames){const c=await comparison(target,a);if(c){used.push({anchor:a,url:c.url,count:c.map.size});for(const [k,v] of c.map){if(pool.has(k))exact.set(k,v);}}}const result=new Map();let reconstructed=0;for(const [k,p] of pool){if(exact.has(k)){result.set(k,{...exact.get(k),name:p.name,pos:p.pos,anchors:anchorNames.filter(a=>anchorMaps[a].has(k)).length});continue;}const ar=anchorNames.map(a=>anchorMaps[a].get(k)?.rank).filter(Number.isFinite);if(ar.length<2)continue;const spread=Math.max(...ar)-Math.min(...ar);if(spread>14)continue;result.set(k,{rank:median(ar),posRank:null,name:p.name,pos:p.pos,exact:false,spread,anchors:ar.length});reconstructed++;}const vals=[...result.values()],exactN=vals.filter(x=>x.exact).length,coverage=vals.length?exactN/vals.length:0,rv=vals.filter(x=>!x.exact),avg=rv.length?rv.reduce((s,x)=>s+x.spread,0)/rv.length:0,max=rv.length?Math.max(...rv.map(x=>x.spread)):0;const quality={ok:vals.length>=120&&exactN>=50&&coverage>=.55&&avg<=9&&max<=14,draftableCount:vals.length,exactDraftableCount:exactN,reconstructedDraftableCount:reconstructed,exactCoverage:coverage,avgSpread:avg,maxSpread:max};return{ok:quality.ok,map:result,quality,comparisons:used};}
const rebuilt={};for(const n of ['Justin Boone','Matt Harmon'])rebuilt[n]=await reconstruct(n);
const allMaps={...anchorMaps,'Justin Boone':rebuilt['Justin Boone'].map,'Matt Harmon':rebuilt['Matt Harmon'].map};
for(const n of ['Justin Boone','Matt Harmon']){const x=rebuilt[n];raw.expert_sources[n]={ok:x.ok,source:'FantasyPros Comparison reconstruction',url:x.comparisons.map(z=>z.url).join(' | '),updated:raw.as_of,count:x.map.size,error:x.ok?'':`quality ${JSON.stringify(x.quality)}`,confidence:x.quality.exactCoverage>=.70?'reconstructed-strong':'reconstructed',exactCount:x.quality.exactDraftableCount,reconstructedCount:x.quality.reconstructedDraftableCount,coverage:x.quality.exactCoverage,quality:x.quality};}
function members(id){const p=PRESETS[id],a=[];for(const [n,w] of p.list){if((raw.expert_sources[n]?.ok||allMaps[n]?.size)&&a.length<p.max)a.push([n,w]);}return a;}
function makePanel(id){const all={};for(const [n,w0] of members(id)){const m=allMaps[n];if(!m)continue;for(const [k,r] of m){if(!pool.has(k))continue;const sw=r.exact===false?Math.max(.55,1-Math.min(10,Number(r.spread)||0)/25):1,w=w0*sw,p=pool.get(k);all[k]??={name:p.name,pos:p.pos,values:[]};all[k].values.push({expertName:n,rank:r.rank,posRank:r.posRank??null,w,baseWeight:w0,exact:r.exact!==false,reconstructed:r.exact===false,spread:Number(r.spread)||0,anchors:Number(r.anchors)||0});}}const out={};for(const[k,v]of Object.entries(all)){const sw=v.values.reduce((s,x)=>s+x.w,0);if(!sw)continue;const mean=v.values.reduce((s,x)=>s+x.rank*x.w,0)/sw,variance=v.values.reduce((s,x)=>s+x.w*(x.rank-mean)**2,0)/sw,pv=v.values.filter(x=>Number.isFinite(x.posRank)),pw=pv.reduce((s,x)=>s+x.w,0);out[k]={name:v.name,pos:v.pos,rank:mean,posRank:pw?pv.reduce((s,x)=>s+x.posRank*x.w,0)/pw:null,sd:Math.sqrt(variance),n:v.values.length,individual:v.values.sort((a,b)=>a.rank-b.rank)};}return out;}
raw.panels={standard:makePanel('standard'),rb:makePanel('rb'),wr:makePanel('wr'),qb:makePanel('qb'),te:makePanel('te')};raw.effective_members=Object.fromEntries(Object.keys(PRESETS).map(id=>[id,members(id)]));for(const r of raw.pool_rows||[]){r.panel_standard=raw.panels.standard[r.key]?.rank??r.panel_standard;r.panel_position=(r.pos==='RB'?raw.panels.rb[r.key]?.rank:r.pos==='WR'?raw.panels.wr[r.key]?.rank:r.pos==='QB'?raw.panels.qb[r.key]?.rank:r.pos==='TE'?raw.panels.te[r.key]?.rank:r.panel_position);}
delete raw.payload_sha256;raw.schema=3;raw.augmentation={method:'Companion-parity FantasyPros dissent-page reconstruction; non-dissent rows only reconstructed when anchor spread <=14',rebuilt:Object.fromEntries(Object.entries(rebuilt).map(([n,x])=>[n,{ok:x.ok,quality:x.quality,comparisons:x.comparisons}]))};raw.payload_sha256=crypto.createHash('sha256').update(JSON.stringify(raw)).digest('hex');fs.writeFileSync(RAW,JSON.stringify(raw,null,2));
const core=['Pat Fitzmaurice','Justin Boone','Andrew Erickson','Derek Brown'],minCoreExperts=core.every(n=>raw.expert_sources[n]?.ok),enoughAdp=(raw.sleeper_adp?.selected_source?.count||0)>=200,pass=minCoreExperts&&raw.candidate_pool_total===230&&enoughAdp;fs.writeFileSync(GATE,JSON.stringify({status:pass?'PASS':'FAIL_CLOSED',as_of:raw.as_of,minCoreExperts,pool_total:raw.candidate_pool_total,sleeper_adp_count:raw.sleeper_adp?.selected_source?.count||0,expert_sources:raw.expert_sources,effective_members:Object.fromEntries(Object.entries(raw.effective_members).map(([k,v])=>[k,v.map(x=>x[0])])),sleeper_diagnostics:raw.sleeper_adp?.diagnostics,payload_sha256:raw.payload_sha256},null,2));console.log(JSON.stringify(JSON.parse(fs.readFileSync(GATE,'utf8')),null,2));
