import fs from 'node:fs';
import crypto from 'node:crypto';
const SEASON='2026', SCORING='HALF';
const POS=new Set(['QB','RB','WR','TE']);
const LIMITS={QB:30,RB:90,WR:80,TE:30};
const PRESETS={
 standard:{list:[['Pat Fitzmaurice',30],['Justin Boone',25],['Sean Koerner',20],['Andrew Erickson',15],['Derek Brown',10]],max:5},
 rb:{list:[['Pat Fitzmaurice',35],['Justin Boone',30],['Sean Koerner',20],['Andrew Erickson',15],['Derek Brown',10]],max:4},
 wr:{list:[['Matt Harmon',35],['Pat Fitzmaurice',30],['Justin Boone',20],['Andrew Erickson',15],['Derek Brown',10]],max:4},
 qb:{list:[['Pat Fitzmaurice',45],['Justin Boone',30],['Sean Koerner',25],['Andrew Erickson',15]],max:3},
 te:{list:[['Pat Fitzmaurice',40],['Justin Boone',25],['Andrew Erickson',20],['Derek Brown',15],['Sean Koerner',15]],max:4}
};
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(jr|sr|ii|iii|iv)\.?\b/g,'').replace(/[^a-z0-9]+/g,'');}
function slugify(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/['’]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');}
function htmlDecode(s){return String(s||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&ndash;|&#8211;/gi,'–').replace(/&mdash;|&#8212;/gi,'—').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)));}
function stripHtml(s){return htmlDecode(String(s||'').replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim();}
async function fetchText(url){const r=await fetch(url,{headers:{accept:'text/html,application/xhtml+xml,application/json','user-agent':'Mozilla/5.0 (compatible; PITTI-Freeze/1.0)'}});if(!r.ok)throw new Error(`HTTP ${r.status} ${url}`);return await r.text();}
function tableRows(html){return [...String(html||'').matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)].map(m=>{const row=m[1],cells=[...row.matchAll(/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(x=>stripHtml(x[1]));return{html:row,cells};}).filter(x=>x.cells.length);}
function parsePosToken(text){const m=String(text||'').toUpperCase().match(/\b(QB|RB|WR|TE|K|DST)\s*[-#]?\s*(\d+)?\b/);return m?{pos:m[1],posRank:m[2]?Number(m[2]):null}:null;}
function parseFantasyProsDirect(html){const out=[],seen=new Set();for(const row of tableRows(html)){if(row.cells.length<3)continue;const rank=Number(String(row.cells[0]).match(/^\s*(\d{1,3})\b/)?.[1]);if(!Number.isFinite(rank)||rank<1||rank>500)continue;let name='';for(const a of row.html.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)){if(/\/nfl\/players\//i.test(a[1]||'')){const t=stripHtml(a[2]);if(/[A-Za-z]/.test(t)){name=t;break;}}}if(!name&&row.cells[1]&&/[A-Za-z]/.test(row.cells[1]))name=row.cells[1];name=name.replace(/\s+\b(Q|O|IR|S)\b\s*$/,'').trim();if(!name||seen.has(norm(name)))continue;let pp=null;for(const c of row.cells){pp=parsePosToken(c);if(pp)break;}if(!pp)continue;seen.add(norm(name));out.push({rank,name,pos:pp.pos,posRank:pp.posRank,exact:true});}return out.sort((a,b)=>a.rank-b.rank);}
function parseYahooSimpleOverall(html){const out=[],seen=new Set();for(const row of tableRows(html)){const c=row.cells;if(c.length<3)continue;const rank=Number(String(c[0]).match(/^\s*(\d{1,3})\b/)?.[1]);if(!Number.isFinite(rank)||rank<1||rank>500)continue;let posInfo=null,posIndex=-1;for(let i=1;i<c.length;i++){const p=parsePosToken(c[i]);if(p){posInfo=p;posIndex=i;break;}}if(!posInfo)continue;let name='';for(let i=1;i<c.length;i++){if(i===posIndex)continue;const t=String(c[i]||'').trim();if(t.length>2&&/[A-Za-z]/.test(t)&&!/^([A-Z]{2,3}|FA)$/.test(t)){name=t;break;}}if(!name||seen.has(norm(name)))continue;seen.add(norm(name));out.push({rank,name,pos:posInfo.pos,posRank:posInfo.posRank,exact:true});}return out.sort((a,b)=>a.rank-b.rank);}
function parseYahooStaffTable(html,expertName){const rows=tableRows(html);let headerIndex=-1,expertCol=-1,playerCol=-1,posCol=-1;const needle=String(expertName||'').toLowerCase();for(let i=0;i<rows.length;i++){const cells=rows[i].cells.map(x=>x.toLowerCase());const ec=cells.findIndex(x=>x.includes(needle)),pc=cells.findIndex(x=>x==='player'||x.includes('player'));if(ec>=0&&pc>=0){headerIndex=i;expertCol=ec;playerCol=pc;posCol=cells.findIndex(x=>x==='pos'||x.includes('position'));break;}}if(headerIndex<0)return[];const out=[],seen=new Set();for(let i=headerIndex+1;i<rows.length;i++){const c=rows[i].cells;if(c.length<=Math.max(expertCol,playerCol))continue;const rank=Number(String(c[expertCol]).match(/(\d{1,3})/)?.[1]),name=String(c[playerCol]||'').trim();if(!Number.isFinite(rank)||!name||seen.has(norm(name)))continue;let pp=posCol>=0?parsePosToken(c[posCol]):null;if(!pp){for(const cell of c){pp=parsePosToken(cell);if(pp)break;}}if(!pp)continue;seen.add(norm(name));out.push({rank,name,pos:pp.pos,posRank:pp.posRank,exact:true});}return out.sort((a,b)=>a.rank-b.rank);}
function fpContext(html){const plain=stripHtml(html);return{yearOk:/\b2026\b/.test(plain),scoringOk:/Half Point PPR Rankings|Half PPR Rankings/i.test(plain),draftOk:/Overall .*Rankings|Draft Rankings/i.test(plain),updated:plain.match(/Rankings\s*-\s*([A-Z][a-z]{2,8}\s+\d{1,2},\s+20\d{2})/i)?.[1]||''};}
function yahooUpdated(html){const plain=stripHtml(html);return plain.match(/Updated\s+(?:[A-Z][a-z]+,?\s+)?([A-Z][a-z]+\s+\d{1,2},\s+2026)/i)?.[1]||plain.match(/([A-Z][a-z]+\s+\d{1,2},\s+2026)/)?.[1]||'';}
const experts={};
async function fp(name){const slug=slugify(name),url=`https://www.fantasypros.com/nfl/rankings/${slug}.php?scoring=HALF&type=draft`;try{const html=await fetchText(url),ctx=fpContext(html),players=parseFantasyProsDirect(html).filter(x=>POS.has(x.pos));if(!(ctx.yearOk&&ctx.scoringOk&&ctx.draftOk))throw new Error(`context ${JSON.stringify(ctx)}`);if(players.length<80)throw new Error(`only ${players.length} skill rows`);experts[name]={ok:true,name,source:'FantasyPros direct',url,updated:ctx.updated,players};}catch(e){experts[name]={ok:false,name,error:String(e.message||e)};}}
async function yahooBoone(){const urls=['https://sports.yahoo.com/fantasy/article/2026-fantasy-football-rankings-justin-boone-top-300-players-155300098.html','https://sports.yahoo.com/fantasy/article/2026-fantasy-football-rankings-justin-boone-top-150-players-155300344.html'];let errors=[];for(const url of urls){try{const html=await fetchText(url),players=parseYahooSimpleOverall(html).filter(x=>POS.has(x.pos));if(players.length>=120){experts['Justin Boone']={ok:true,name:'Justin Boone',source:'Yahoo Sports',url,updated:yahooUpdated(html),players};return;}errors.push(`${players.length} rows`);}catch(e){errors.push(e.message);}}experts['Justin Boone']={ok:false,name:'Justin Boone',error:errors.join(' | ')};}
async function yahooHarmon(){const urls=['https://sports.yahoo.com/fantasy/article/fantasy-football-rankings-consensus-top-300-players-160643696.html','https://ca.sports.yahoo.com/news/fantasy-football-rankings-consensus-top-300-players-160643696.html'];let errors=[];for(const url of urls){try{const html=await fetchText(url),players=parseYahooStaffTable(html,'Matt Harmon').filter(x=>POS.has(x.pos));if(players.length>=80){experts['Matt Harmon']={ok:true,name:'Matt Harmon',source:'Yahoo Sports Staff',url,updated:yahooUpdated(html),players};return;}errors.push(`${players.length} rows`);}catch(e){errors.push(e.message);}}experts['Matt Harmon']={ok:false,name:'Matt Harmon',error:errors.join(' | ')};}
await Promise.all([fp('Pat Fitzmaurice'),fp('Andrew Erickson'),fp('Derek Brown'),yahooBoone(),yahooHarmon()]);
experts['Sean Koerner']={ok:false,name:'Sean Koerner',error:'No deterministic complete current all-position public feed configured; retain degraded/unavailable status.'};
const okNames=Object.keys(experts).filter(n=>experts[n].ok);
function buildPool(){const buckets={QB:new Map(),RB:new Map(),WR:new Map(),TE:new Map()};for(const n of okNames){for(const row of experts[n].players){const k=norm(row.name);if(!buckets[row.pos])continue;const cur=buckets[row.pos].get(k)||{key:k,name:row.name,pos:row.pos,ranks:[]};cur.ranks.push(row.rank);buckets[row.pos].set(k,cur);}}const keep=new Set(),counts={};for(const [pos,limit] of Object.entries(LIMITS)){const list=[...buckets[pos].values()].map(x=>({...x,best:Math.min(...x.ranks),mean:x.ranks.reduce((a,b)=>a+b,0)/x.ranks.length,mentions:x.ranks.length})).sort((a,b)=>a.best-b.best||a.mean-b.mean||b.mentions-a.mentions||a.name.localeCompare(b.name));const chosen=list.slice(0,limit);chosen.forEach(x=>keep.add(x.key));counts[pos]=chosen.length;}return{keep,counts,total:keep.size};}
const pool=buildPool();
function membersFor(pid){const p=PRESETS[pid],out=[];for(const [name,w] of p.list){if(experts[name]?.ok&&out.length<p.max)out.push([name,w]);}return out;}
function panel(pid){const members=membersFor(pid),all={};for(const [name,w] of members){for(const row of experts[name].players){const k=norm(row.name);if(!pool.keep.has(k))continue;all[k]??={name:row.name,pos:row.pos,values:[]};all[k].values.push({expertName:name,rank:row.rank,posRank:row.posRank??null,w,baseWeight:w,exact:true,reconstructed:false});}}const out={};for(const [k,v] of Object.entries(all)){const sw=v.values.reduce((s,x)=>s+x.w,0);if(!sw)continue;const mean=v.values.reduce((s,x)=>s+x.rank*x.w,0)/sw,variance=v.values.reduce((s,x)=>s+x.w*(x.rank-mean)**2,0)/sw;const pv=v.values.filter(x=>Number.isFinite(x.posRank)),pw=pv.reduce((s,x)=>s+x.w,0);out[k]={name:v.name,pos:v.pos,rank:mean,posRank:pw?pv.reduce((s,x)=>s+x.posRank*x.w,0)/pw:null,sd:Math.sqrt(variance),n:v.values.length,individual:v.values.sort((a,b)=>a.rank-b.rank)};}return out;}
const panels={standard:panel('standard'),rb:panel('rb'),wr:panel('wr'),qb:panel('qb'),te:panel('te')};
async function sleeper(){const positions=['QB','RB','WR','TE'].map(p=>`position[]=${encodeURIComponent(p)}`).join('&');const candidates=[
 {id:'legacy-season-api-sleeper-app',url:`https://api.sleeper.app/projections/nfl/2026?season_type=regular&${positions}&order_by=adp_half_ppr`,fields:['adp_half_ppr','adp_half']},
 {id:'week1-api-sleeper-com',url:`https://api.sleeper.com/projections/nfl/2026/1?season_type=regular&${positions}&order_by=adp_dd_ppr`,fields:['adp_dd_ppr','adp_half_ppr','adp_half']},
 {id:'week1-api-sleeper-app',url:`https://api.sleeper.app/projections/nfl/2026/1?season_type=regular&${positions}&order_by=adp_dd_ppr`,fields:['adp_dd_ppr','adp_half_ppr','adp_half']}
 ];let players={};try{players=JSON.parse(await fetchText('https://api.sleeper.app/v1/players/nfl'));}catch(e){}
 const diag=[];let best=null;for(const c of candidates){try{const raw=JSON.parse(await fetchText(c.url)),arr=Array.isArray(raw)?raw:[],vals=[];const fieldCounts={};for(const row of arr){let val=null,field=null;for(const f of c.fields){const x=row?.stats?.[f]??row?.[f];if(Number.isFinite(Number(x))&&Number(x)>0&&Number(x)<999){val=Number(x);field=f;break;}}if(field)fieldCounts[field]=(fieldCounts[field]||0)+1;const pid=String(row.player_id||row.player?.player_id||''),meta=players[pid]||row.player||{},name=meta.full_name||[meta.first_name,meta.last_name].filter(Boolean).join(' ');if(name&&val!=null)vals.push({player_id:pid,name,adp:val,field});}vals.sort((a,b)=>a.adp-b.adp);diag.push({id:c.id,url:c.url,http_rows:arr.length,count:vals.length,fieldCounts});if(!best||vals.length>best.players.length)best={...c,players:vals,fieldCounts};}catch(e){diag.push({id:c.id,url:c.url,error:String(e.message||e),count:0});}}
 return{diagnostics:diag,best};}
const adp=await sleeper();
const adpMap={};for(const r of adp.best?.players||[])adpMap[norm(r.name)]=r.adp;
const poolRows=[...pool.keep].map(k=>{const s=panels.standard[k]||panels.rb[k]||panels.wr[k]||panels.qb[k]||panels.te[k];return{key:k,name:s?.name||k,pos:s?.pos||'',panel_standard:panels.standard[k]?.rank??null,panel_position:(s?.pos==='RB'?panels.rb[k]?.rank:s?.pos==='WR'?panels.wr[k]?.rank:s?.pos==='QB'?panels.qb[k]?.rank:s?.pos==='TE'?panels.te[k]?.rank:null),adp:adpMap[k]??null};}).sort((a,b)=>(a.panel_standard??999)-(b.panel_standard??999));
const output={schema:1,as_of:new Date().toISOString(),season:2026,scoring:'HALF_PPR',expert_sources:Object.fromEntries(Object.entries(experts).map(([n,e])=>[n,{ok:e.ok,source:e.source||'',url:e.url||'',updated:e.updated||'',count:e.players?.length||0,error:e.error||''}])),effective_members:Object.fromEntries(Object.keys(PRESETS).map(id=>[id,membersFor(id)])),candidate_pool_counts:pool.counts,candidate_pool_total:pool.total,sleeper_adp:{selected_source:adp.best?{id:adp.best.id,url:adp.best.url,count:adp.best.players.length,fieldCounts:adp.best.fieldCounts}:null,diagnostics:adp.diagnostics},panels,pool_rows:poolRows};
const canon=JSON.stringify(output);output.payload_sha256=crypto.createHash('sha256').update(canon).digest('hex');fs.writeFileSync('FRESH_2026_MARKET_PANEL_RAW.json',JSON.stringify(output,null,2));
const minExperts=['Pat Fitzmaurice','Justin Boone','Andrew Erickson','Derek Brown'].every(n=>experts[n]?.ok);const enoughAdp=(adp.best?.players.length||0)>=200;const pass=minExperts&&pool.total===230&&enoughAdp;
fs.writeFileSync('FRESH_2026_MARKET_PANEL_GATE.json',JSON.stringify({status:pass?'PASS':'FAIL_CLOSED',as_of:output.as_of,minCoreExperts:minExperts,pool_total:pool.total,sleeper_adp_count:adp.best?.players.length||0,expert_sources:output.expert_sources,sleeper_diagnostics:adp.diagnostics,payload_sha256:output.payload_sha256},null,2));
console.log(JSON.stringify(JSON.parse(fs.readFileSync('FRESH_2026_MARKET_PANEL_GATE.json','utf8')),null,2));
