import fs from 'node:fs';
import crypto from 'node:crypto';
const SEASON='2026',SCORING='HALF';
const POS=new Set(['QB','RB','WR','TE']);
const ALLPOS=new Set(['QB','RB','WR','TE','K','DST']);
const LIMITS={QB:30,RB:90,WR:80,TE:30};
const PRESETS={
 standard:{list:[['Pat Fitzmaurice',30],['Justin Boone',25],['Sean Koerner',20],['Andrew Erickson',15],['Derek Brown',10]],max:5},
 rb:{list:[['Pat Fitzmaurice',35],['Justin Boone',30],['Sean Koerner',20],['Andrew Erickson',15],['Derek Brown',10]],max:4},
 wr:{list:[['Matt Harmon',35],['Pat Fitzmaurice',30],['Justin Boone',20],['Andrew Erickson',15],['Derek Brown',10]],max:4},
 qb:{list:[['Pat Fitzmaurice',45],['Justin Boone',30],['Sean Koerner',25],['Andrew Erickson',15]],max:3},
 te:{list:[['Pat Fitzmaurice',40],['Justin Boone',25],['Andrew Erickson',20],['Derek Brown',15],['Sean Koerner',15]],max:4}
};
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(jr|sr|ii|iii|iv)\.?\b/g,'').replace(/[^a-z0-9]+/g,'');}
function slugify(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/['’]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');}
function htmlDecode(s){return String(s||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&ndash;|&#8211;/gi,'–').replace(/&mdash;|&#8212;/gi,'—').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)));}
function stripHtml(s){return htmlDecode(String(s||'').replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim();}
async function fetchText(url){const r=await fetch(url,{headers:{accept:'text/html,application/xhtml+xml,application/json','user-agent':'Mozilla/5.0 (compatible; PITTI-Freeze/2.0)'}});if(!r.ok)throw new Error(`HTTP ${r.status} ${url}`);return await r.text();}
function tableRows(html){return [...String(html||'').matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)].map(m=>{const row=m[1],cells=[...row.matchAll(/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(x=>stripHtml(x[1]));return{html:row,cells};}).filter(x=>x.cells.length);}
function parsePosToken(text){const m=String(text||'').toUpperCase().match(/\b(QB|RB|WR|TE|K|DST)\s*[-#]?\s*(\d+)?\b/);return m?{pos:m[1],posRank:m[2]?Number(m[2]):null}:null;}
function parseFantasyProsDirect(html){const out=[],seen=new Set();for(const row of tableRows(html)){if(row.cells.length<3)continue;const rank=Number(String(row.cells[0]).match(/^\s*(\d{1,3})\b/)?.[1]);if(!Number.isFinite(rank)||rank<1||rank>500)continue;let name='';for(const a of row.html.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)){if(/\/nfl\/players\//i.test(a[1]||'')){const t=stripHtml(a[2]);if(/[A-Za-z]/.test(t)){name=t;break;}}}if(!name&&row.cells[1]&&/[A-Za-z]/.test(row.cells[1]))name=row.cells[1];name=name.replace(/\s+\b(Q|O|IR|S)\b\s*$/,'').trim();if(!name||seen.has(norm(name)))continue;let pp=null;for(const c of row.cells){pp=parsePosToken(c);if(pp)break;}if(!pp)continue;seen.add(norm(name));out.push({rank,name,pos:pp.pos,posRank:pp.posRank,exact:true,spread:0,anchors:0});}return out.sort((a,b)=>a.rank-b.rank);}
function fpContext(html){const plain=stripHtml(html);return{yearOk:/\b2026\b/.test(plain),scoringOk:/Half Point PPR Rankings|Half PPR Rankings|\bHALF\b/i.test(plain),draftOk:/Overall .*Rankings|Draft Rankings|Dissenting Opinions/i.test(plain),updated:plain.match(/(?:Rankings\s*-\s*|Updated\s+)([A-Z][a-z]{2,8}\s+\d{1,2},\s+20\d{2})/i)?.[1]||''};}
async function direct(name){const slug=slugify(name),url=`https://www.fantasypros.com/nfl/rankings/${slug}.php?scoring=HALF&type=draft`;try{const html=await fetchText(url),ctx=fpContext(html),players=parseFantasyProsDirect(html).filter(x=>ALLPOS.has(x.pos));if(!(ctx.yearOk&&ctx.scoringOk&&ctx.draftOk))throw new Error(`context ${JSON.stringify(ctx)}`);if(players.filter(x=>POS.has(x.pos)).length<80)throw new Error(`only ${players.length} rows`);return{ok:true,name,source:'FantasyPros direct',url,updated:ctx.updated,players,confidence:'exact',exactCount:players.length,reconstructedCount:0,coverage:1};}catch(e){return{ok:false,name,error:String(e.message||e)};}}
function playerCellInfo(s){const t=String(s||'').trim();let pp=parsePosToken(t);if(!pp)return null;let name=t.replace(/\s+[A-Z]{2,3}\s*-\s*(QB|RB|WR|TE|K|DST)\b.*$/i,'').replace(/\s+(QB|RB|WR|TE|K|DST)\s*\d*\s*$/i,'').trim();if(!name||name.length<2)return null;return{name,pos:pp.pos};}
function parseComparisonTarget(html,targetName){const rows=tableRows(html),needle=String(targetName).toLowerCase(),out=new Map();let targetCol=-1,playerCol=-1;for(const row of rows){const lc=row.cells.map(x=>String(x).toLowerCase());const tc=lc.findIndex(x=>x.includes(needle)&&x.includes('rank'));const pc=lc.findIndex(x=>x==='player'||x.includes('player'));if(tc>=0&&pc>=0){targetCol=tc;playerCol=pc;continue;}if(targetCol<0||playerCol<0||row.cells.length<=Math.max(targetCol,playerCol))continue;const rank=Number(String(row.cells[targetCol]).match(/\d{1,3}/)?.[0]);if(!Number.isFinite(rank)||rank<1||rank>500)continue;const info=playerCellInfo(row.cells[playerCol]);if(!info)continue;out.set(norm(info.name),{name:info.name,pos:info.pos,rank,exact:true,spread:0,anchors:0});}return out;}
async function comparison(target,anchor){const ts=slugify(target),as=slugify(anchor),urls=[`https://www.fantasypros.com/nfl/rankings/${as}-${ts}.php?scoring=HALF&type=draft`,`https://www.fantasypros.com/nfl/rankings/${ts}-${as}.php?scoring=HALF&type=draft`];for(const url of urls){try{const html=await fetchText(url),ctx=fpContext(html),rows=parseComparisonTarget(html,target);if(ctx.yearOk&&ctx.draftOk&&rows.size>=10)return{ok:true,url,rows,count:rows.size};}catch(e){}}return{ok:false};}
function median(a){const x=[...a].sort((a,b)=>a-b),n=x.length;return n%2?x[(n-1)/2]:(x[n/2-1]+x[n/2])/2;}
async function reconstruct(target,anchorData){const anchors=Object.keys(anchorData).filter(n=>anchorData[n]?.ok);if(anchors.length<2)return{ok:false,name:target,error:`only ${anchors.length} anchors`};const exact=new Map(),comparisons=[];for(const a of anchors){const c=await comparison(target,a);if(c.ok){comparisons.push({anchor:a,url:c.url,count:c.count});for(const [k,v] of c.rows){const prev=exact.get(k);if(!prev||prev.rank===v.rank)exact.set(k,v);}}}if(!comparisons.length||exact.size<20)return{ok:false,name:target,error:`only ${exact.size} exact comparison ranks`};const universe=new Map();for(const a of anchors){for(const r of anchorData[a].players){const k=norm(r.name),u=universe.get(k)||{name:r.name,pos:r.pos,anchorRanks:[]};u.anchorRanks.push(Number(r.rank));universe.set(k,u);}}const players=[];for(const [k,u] of universe){const e=exact.get(k);if(e){players.push({...e,anchors:u.anchorRanks.length});continue;}const ar=u.anchorRanks.filter(Number.isFinite);if(!ar.length)continue;const m=median(ar),spread=Math.max(...ar)-Math.min(...ar);players.push({name:u.name,pos:u.pos,rank:m,posRank:null,exact:false,spread,anchors:ar.length});}players.sort((a,b)=>a.rank-b.rank||Number(b.exact)-Number(a.exact)||a.name.localeCompare(b.name));const draftable=players.filter(x=>POS.has(x.pos)),exactD=draftable.filter(x=>x.exact),reconD=draftable.filter(x=>!x.exact);const avgSpread=reconD.length?reconD.reduce((s,x)=>s+x.spread,0)/reconD.length:0,maxSpread=reconD.length?Math.max(...reconD.map(x=>x.spread)):0;const quality={draftableCount:draftable.length,exactDraftableCount:exactD.length,reconstructedDraftableCount:reconD.length,exactCoverage:draftable.length?exactD.length/draftable.length:0,avgSpread,maxSpread};quality.ok=draftable.length>=120&&exactD.length>=50&&quality.exactCoverage>=.20&&avgSpread<=12&&maxSpread<=35;if(!quality.ok)return{ok:false,name:target,error:`reconstruction quality fail ${JSON.stringify(quality)}`,quality};return{ok:true,name:target,source:'FantasyPros Comparison reconstruction',url:comparisons.map(x=>x.url).join(' | '),updated:'',players,confidence:quality.exactCoverage>=.70?'reconstructed-strong':'reconstructed',exactCount:players.filter(x=>x.exact).length,reconstructedCount:players.filter(x=>!x.exact).length,coverage:players.length?players.filter(x=>x.exact).length/players.length:0,quality,comparisons};}
const experts={};
const anchors={};for(const n of ['Pat Fitzmaurice','Andrew Erickson','Derek Brown']){anchors[n]=await direct(n);experts[n]=anchors[n];}
for(const n of ['Justin Boone','Matt Harmon']){let d=await direct(n);if(!d.ok)d=await reconstruct(n,anchors);experts[n]=d;}
experts['Sean Koerner']={ok:false,name:'Sean Koerner',error:'No deterministic complete current all-position public feed configured; retain degraded/unavailable status.'};
const okNames=Object.keys(experts).filter(n=>experts[n].ok);
function buildPool(){const buckets={QB:new Map(),RB:new Map(),WR:new Map(),TE:new Map()};for(const n of okNames){for(const row of experts[n].players){if(!POS.has(row.pos))continue;const k=norm(row.name),cur=buckets[row.pos].get(k)||{key:k,name:row.name,pos:row.pos,ranks:[]};cur.ranks.push(row.rank);buckets[row.pos].set(k,cur);}}const keep=new Set(),counts={};for(const [pos,limit] of Object.entries(LIMITS)){const list=[...buckets[pos].values()].map(x=>({...x,best:Math.min(...x.ranks),mean:x.ranks.reduce((a,b)=>a+b,0)/x.ranks.length,mentions:x.ranks.length})).sort((a,b)=>a.best-b.best||a.mean-b.mean||b.mentions-a.mentions||a.name.localeCompare(b.name));const chosen=list.slice(0,limit);chosen.forEach(x=>keep.add(x.key));counts[pos]=chosen.length;}return{keep,counts,total:keep.size};}
const pool=buildPool();
function membersFor(pid){const p=PRESETS[pid],out=[];for(const [name,w] of p.list){if(experts[name]?.ok&&out.length<p.max)out.push([name,w]);}return out;}
function panel(pid){const members=membersFor(pid),all={};for(const [name,w0] of members){for(const row of experts[name].players){if(!POS.has(row.pos))continue;const k=norm(row.name);if(!pool.keep.has(k))continue;const sourceWeight=row.exact===false?Math.max(.55,1-Math.min(10,Number(row.spread)||0)/25):1,w=w0*sourceWeight;all[k]??={name:row.name,pos:row.pos,values:[]};all[k].values.push({expertName:name,rank:row.rank,posRank:row.posRank??null,w,baseWeight:w0,exact:row.exact!==false,reconstructed:row.exact===false,spread:Number(row.spread)||0,anchors:Number(row.anchors)||0});}}const out={};for(const [k,v] of Object.entries(all)){const sw=v.values.reduce((s,x)=>s+x.w,0);if(!sw)continue;const mean=v.values.reduce((s,x)=>s+x.rank*x.w,0)/sw,variance=v.values.reduce((s,x)=>s+x.w*(x.rank-mean)**2,0)/sw;const pv=v.values.filter(x=>Number.isFinite(x.posRank)),pw=pv.reduce((s,x)=>s+x.w,0);out[k]={name:v.name,pos:v.pos,rank:mean,posRank:pw?pv.reduce((s,x)=>s+x.posRank*x.w,0)/pw:null,sd:Math.sqrt(variance),n:v.values.length,individual:v.values.sort((a,b)=>a.rank-b.rank)};}return out;}
const panels={standard:panel('standard'),rb:panel('rb'),wr:panel('wr'),qb:panel('qb'),te:panel('te')};
async function sleeper(){const positions=['QB','RB','WR','TE'].map(p=>`position[]=${encodeURIComponent(p)}`).join('&'),candidates=[{id:'legacy-season-api-sleeper-app',url:`https://api.sleeper.app/projections/nfl/2026?season_type=regular&${positions}&order_by=adp_half_ppr`,fields:['adp_half_ppr','adp_half']},{id:'week1-api-sleeper-com',url:`https://api.sleeper.com/projections/nfl/2026/1?season_type=regular&${positions}&order_by=adp_dd_ppr`,fields:['adp_dd_ppr','adp_half_ppr','adp_half']},{id:'week1-api-sleeper-app',url:`https://api.sleeper.app/projections/nfl/2026/1?season_type=regular&${positions}&order_by=adp_dd_ppr`,fields:['adp_dd_ppr','adp_half_ppr','adp_half']}];let players={};try{players=JSON.parse(await fetchText('https://api.sleeper.app/v1/players/nfl'));}catch(e){}const diag=[];let best=null;for(const c of candidates){try{const raw=JSON.parse(await fetchText(c.url)),arr=Array.isArray(raw)?raw:[],vals=[],fieldCounts={};for(const row of arr){let val=null,field=null;for(const f of c.fields){const x=row?.stats?.[f]??row?.[f];if(Number.isFinite(Number(x))&&Number(x)>0&&Number(x)<999){val=Number(x);field=f;break;}}if(field)fieldCounts[field]=(fieldCounts[field]||0)+1;const pid=String(row.player_id||row.player?.player_id||''),meta=players[pid]||row.player||{},name=meta.full_name||[meta.first_name,meta.last_name].filter(Boolean).join(' ');if(name&&val!=null)vals.push({player_id:pid,name,adp:val,field});}vals.sort((a,b)=>a.adp-b.adp);diag.push({id:c.id,url:c.url,http_rows:arr.length,count:vals.length,fieldCounts});if(!best||vals.length>best.players.length)best={...c,players:vals,fieldCounts};}catch(e){diag.push({id:c.id,url:c.url,error:String(e.message||e),count:0});}}return{diagnostics:diag,best};}
const adp=await sleeper(),adpMap={};for(const r of adp.best?.players||[])adpMap[norm(r.name)]=r.adp;
const poolRows=[...pool.keep].map(k=>{const s=panels.standard[k]||panels.rb[k]||panels.wr[k]||panels.qb[k]||panels.te[k];return{key:k,name:s?.name||k,pos:s?.pos||'',panel_standard:panels.standard[k]?.rank??null,panel_position:(s?.pos==='RB'?panels.rb[k]?.rank:s?.pos==='WR'?panels.wr[k]?.rank:s?.pos==='QB'?panels.qb[k]?.rank:s?.pos==='TE'?panels.te[k]?.rank:null),adp:adpMap[k]??null};}).sort((a,b)=>(a.panel_standard??999)-(b.panel_standard??999));
const output={schema:2,as_of:new Date().toISOString(),season:2026,scoring:'HALF_PPR',expert_sources:Object.fromEntries(Object.entries(experts).map(([n,e])=>[n,{ok:e.ok,source:e.source||'',url:e.url||'',updated:e.updated||'',count:e.players?.filter(x=>POS.has(x.pos)).length||0,error:e.error||'',confidence:e.confidence||'',exactCount:e.exactCount||0,reconstructedCount:e.reconstructedCount||0,coverage:e.coverage||0,quality:e.quality||null}])),effective_members:Object.fromEntries(Object.keys(PRESETS).map(id=>[id,membersFor(id)])),candidate_pool_counts:pool.counts,candidate_pool_total:pool.total,sleeper_adp:{selected_source:adp.best?{id:adp.best.id,url:adp.best.url,count:adp.best.players.length,fieldCounts:adp.best.fieldCounts}:null,diagnostics:adp.diagnostics},panels,pool_rows:poolRows};
const canon=JSON.stringify(output);output.payload_sha256=crypto.createHash('sha256').update(canon).digest('hex');fs.writeFileSync('FRESH_2026_MARKET_PANEL_RAW.json',JSON.stringify(output,null,2));
const core=['Pat Fitzmaurice','Justin Boone','Andrew Erickson','Derek Brown'],minExperts=core.every(n=>experts[n]?.ok),enoughAdp=(adp.best?.players.length||0)>=200,positionCoverage=Object.fromEntries(Object.keys(PRESETS).map(id=>[id,membersFor(id).map(x=>x[0])])),pass=minExperts&&pool.total===230&&enoughAdp;
fs.writeFileSync('FRESH_2026_MARKET_PANEL_GATE.json',JSON.stringify({status:pass?'PASS':'FAIL_CLOSED',as_of:output.as_of,minCoreExperts:minExperts,pool_total:pool.total,sleeper_adp_count:adp.best?.players.length||0,expert_sources:output.expert_sources,effective_members:positionCoverage,sleeper_diagnostics:adp.diagnostics,payload_sha256:output.payload_sha256},null,2));
console.log(JSON.stringify(JSON.parse(fs.readFileSync('FRESH_2026_MARKET_PANEL_GATE.json','utf8')),null,2));
