'use strict';
/* Diagnostic-only analysis of the preregistered direct 2.02 raw artifact.
   No outcome model and no scalar policy winner. */
const fs=require('fs');
const IN='counterfactual_2026/RC459_DIRECT_2_02_CANDIDATES_2026.json';
const OUT='counterfactual_2026/RC459_DIRECT_2_02_DIAGNOSTIC_2026.json';
const x=JSON.parse(fs.readFileSync(IN,'utf8'));if(x.status!=='PASS'||!x.raw_only||x.outcome_evaluated!==false)throw Error('raw gate');
const rank=p=>Number.isFinite(p.panel)?p.panel:9999, adp=p=>Number.isFinite(p.adp)?p.adp:9999;
function lineupPanel(r){const q=r.filter(p=>p.pos==='QB').sort((a,b)=>rank(a)-rank(b)),rb=r.filter(p=>p.pos==='RB').sort((a,b)=>rank(a)-rank(b)),wr=r.filter(p=>p.pos==='WR').sort((a,b)=>rank(a)-rank(b)),te=r.filter(p=>p.pos==='TE').sort((a,b)=>rank(a)-rank(b));if(!q.length||!rb.length||wr.length<2||!te.length)return null;const used=[q[0],rb[0],wr[0],wr[1],te[0]],ids=new Set(used.map(p=>p.key)),flex=r.filter(p=>['RB','WR','TE'].includes(p.pos)&&!ids.has(p.key)).sort((a,b)=>rank(a)-rank(b)).slice(0,2);if(flex.length<2)return null;return [...used,...flex].reduce((s,p)=>s+rank(p),0)}
function depthGap(b,pos){const roster=b.user_roster.filter(p=>p.pos===pos&&Number.isFinite(p.panel));const fa=b.free_agent_ids.map(id=>x.player_pool_snapshot[id]).filter(p=>p&&p.pos===pos&&Number.isFinite(p.panel));if(!roster.length||!fa.length)return null;const worst=Math.max(...roster.map(p=>p.panel)),best=Math.min(...fa.map(p=>p.panel));return worst-best}
const rows=[];for(const s of x.states){for(const b of s.branches){rows.push({state:s.prefix_fingerprint,seed:s.seed,p109:s.forced_1_09.name,candidate:b.candidate.name,pos:b.candidate.pos,lineup_panel:lineupPanel(b.user_roster),total_panel:b.user_roster.reduce((z,p)=>z+(Number.isFinite(p.panel)?p.panel:0),0),total_adp:b.user_roster.reduce((z,p)=>z+(Number.isFinite(p.adp)?p.adp:0),0),rb_worst_minus_best_fa:depthGap(b,'RB'),wr_worst_minus_best_fa:depthGap(b,'WR')})}}
const metrics=['lineup_panel','total_panel','total_adp'];for(const st of new Set(rows.map(r=>r.state))){const rr=rows.filter(r=>r.state===st);for(const m of metrics){const vals=rr.map(r=>r[m]).filter(Number.isFinite).sort((a,b)=>a-b);for(const r of rr)if(Number.isFinite(r[m]))r[m+'_rank']=1+vals.filter(v=>v<r[m]).length+(vals.filter(v=>v===r[m]).length-1)/2}}
const groups={};for(const r of rows){(groups[r.candidate]??=[]).push(r)}const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null;const candidate_summary=Object.entries(groups).map(([candidate,g])=>({candidate,n:g.length,mean_within_state_lineup_rank:mean(g.map(r=>r.lineup_panel_rank).filter(Number.isFinite)),mean_within_state_total_panel_rank:mean(g.map(r=>r.total_panel_rank).filter(Number.isFinite)),mean_within_state_total_adp_rank:mean(g.map(r=>r.total_adp_rank).filter(Number.isFinite)),mean_rb_worst_minus_best_fa:mean(g.map(r=>r.rb_worst_minus_best_fa).filter(Number.isFinite)),mean_wr_worst_minus_best_fa:mean(g.map(r=>r.wr_worst_minus_best_fa).filter(Number.isFinite))})).sort((a,b)=>a.mean_within_state_lineup_rank-b.mean_within_state_lineup_rank);
const out={schema:1,status:'PASS',diagnostic_only:true,no_scalar_winner:true,raw_source_sha256:'2b8f3758b3c9f1331f7c75356a8b7956b4006f164a3718f77cf21442afb195be',states:x.states.length,branches:rows.length,interpretation:'Lower within-state ranks are better. lineup_panel uses selected-panel ranks and is not an independent outcome model. total_adp is a market-regret diagnostic. Positive worst-minus-best-FA means the worst drafted player at that position is worse than the best actual FA.',candidate_summary};fs.writeFileSync(OUT,JSON.stringify(out,null,2));console.log(JSON.stringify({status:'PASS',states:out.states,branches:out.branches,top_lineup:candidate_summary.slice(0,8).map(z=>[z.candidate,+z.mean_within_state_lineup_rank.toFixed(2)]),output:OUT},null,2));