'use strict';
/* Sensitivity analysis: same verified Sleeper half-PPR anchors and Dutch profile,
   vary only early market dispersion. No strategy certification. */
const fs=require('fs'),crypto=require('crypto');
const M=JSON.parse(fs.readFileSync('research/SLEEPER_HALF_PPR_MARKET_ANCHORS_2026-08-23.json','utf8')),market=M.adp;
const CORE='research/rc459_decision_counterfactual_screen_2026.js',raw=fs.readFileSync(CORE,'utf8'),buf=Buffer.from(raw),EXPECT='8cd71b5d01af8fe0f03ab0ff9ee3573486d4b5c3';
const blob=crypto.createHash('sha1').update(Buffer.from(`blob ${buf.length}\0`)).update(buf).digest('hex');if(blob!==EXPECT)throw Error('CORE_DRIFT');const main=raw.indexOf('(async()=>'),exp=`\nreturn {getFixture,apiFrom,init,clone,advance,earlyLegal,force,ok};`;const C=new Function('require','fetch','structuredClone',raw.slice(0,main)+exp)(require,fetch,structuredClone);const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const taus=[1.35,1.8,2.4,3.2,4.2],seedN=300,pick9Max=14,targets=['James Cook III','CeeDee Lamb','Saquon Barkley','Ashton Jeanty',"De'Von Achane",'Justin Jefferson'];
function install(api,tau0){const old=api.oppWeight;api.oppWeight=(p,pn,c,name,stress)=>{const m=market[p.name];if(pn>32||!Number.isFinite(m))return old(p,pn,c,name,stress);const oldTau=(pn<=30?1.35:4.5)*(stress==='stress'?1.18:1),newTau=(pn<=30?tau0:Math.max(4.5,tau0))*(stress==='stress'?1.18:1),oldCenter=.90*p.adp+.10*p.panel,oldMk=Math.exp(clamp((pn-oldCenter)/oldTau,-9,3.8)),nonMk=Math.max(.00005,old(p,pn,c,name,stress))/Math.max(.00005,oldMk),newMk=Math.exp(clamp((pn-m)/newTau,-9,3.8));return Math.max(.00005,newMk*nonMk)}}
(async()=>{const fix=await C.getFixture(),all={};for(const tau of taus){const api=C.apiFrom(fix);await api.loadMeta();install(api,tau);const players=api.buildPlayers();api.initRepl(players);const skill=new Set(['RB','WR']),pByName=Object.fromEntries(Object.values(players).map(p=>[p.name,p])),control9=new Set(M.strategy_exclusions['1.09_major_reach_controls']);const conditional={},avail9={};for(const n of targets)avail9[n]={n:0,a:0};let states=0;
 for(let i=0;i<seedN;i++){const seed=459601001+i,pre9=C.advance(api,players,C.init(api,players,seed),9,'MARKET_NEUTRAL');for(const n of targets){avail9[n].n++;if([...pre9.available].some(k=>players[k]?.name===n))avail9[n].a++}const cands=[...pre9.available].map(k=>players[k]).filter(Boolean).filter(p=>skill.has(p.pos)&&Number.isFinite(market[p.name])&&market[p.name]<=pick9Max&&!control9.has(p.name));for(const c9 of cands){const s=C.clone(pre9);C.force(api,s,c9,9);C.advance(api,players,s,12,'MARKET_NEUTRAL');states++;const av=new Set([...s.available].map(k=>players[k]?.name));for(const n of targets){if(n===c9.name)continue;const key=c9.name+' -> '+n,z=conditional[key]||(conditional[key]={pick9:c9.name,target:n,n:0,a:0});z.n++;if(av.has(n))z.a++}}}
 for(const z of Object.values(conditional))z.rate=z.a/z.n;for(const z of Object.values(avail9))z.rate=z.a/z.n;all[String(tau)]={states,pick9:avail9,conditional};}
 const focus={};for(const [tau,r] of Object.entries(all)){focus[tau]={};for(const key of ['Ashton Jeanty -> Justin Jefferson','Justin Jefferson -> Ashton Jeanty','James Cook III -> Justin Jefferson','Justin Jefferson -> James Cook III','CeeDee Lamb -> Justin Jefferson','Justin Jefferson -> CeeDee Lamb','Ashton Jeanty -> CeeDee Lamb','CeeDee Lamb -> Ashton Jeanty'])focus[tau][key]=r.conditional[key]?.rate??null}
 const out={schema:1,status:'PASS',strategy_certified:false,market:M.source,taus,seedN,results:all,focus};fs.mkdirSync('counterfactual_2026',{recursive:true});fs.writeFileSync('counterfactual_2026/RC459_TURN12_MARKET_DISPERSION_SENSITIVITY_2026.json',JSON.stringify(out,null,2));console.log(JSON.stringify({status:'PASS',focus},null,2))})().catch(e=>{console.error(e.stack||e);process.exit(2)});