'use strict';
/* Research-only causal plumbing screen on the ACTUAL validated rc4.59 full-policy kernel.
   No outcome evaluator and no production policy changes. First objective: prove that
   picks 1-8 / 1-11 are shared exactly, treatment alone branches the state, and the
   validated opponent kernel resumes deterministically from a cloned RNG snapshot. */
const fs=require('fs'),crypto=require('crypto');
const SRC='research/rc459_full_policy_paired_2026.js';
const LEG="function rng(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}";
const ST="function rng(seedOrState){let a=(typeof seedOrState==='object'?seedOrState.a:seedOrState)>>>0;let draws=(typeof seedOrState==='object'?(seedOrState.draws||0):0)>>>0;const r=function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;draws++;return((t^t>>>14)>>>0)/4294967296};r.snapshot=()=>({a:a>>>0,draws});r.clone=()=>rng(r.snapshot());return r}";
function stable(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(v instanceof Set)return stable([...v].sort());if(Array.isArray(v))return '['+v.map(stable).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}'}
function sha(v){return crypto.createHash('sha256').update(typeof v==='string'?v:stable(v)).digest('hex')}
function assert(x,m){if(!x)throw Error('CF_PLUMBING_INVARIANT: '+m)}
async function fixture(){const r=await fetch('https://api.sleeper.app/v1/players/nfl',{headers:{'User-Agent':'PITTI-CF-Plumbing/1.0'}});if(!r.ok)throw Error('Sleeper '+r.status);const j=await r.json();if(Object.keys(j||{}).length<1000)throw Error('metadata fixture implausible');return j}
function buildApi(fix){
  let src=fs.readFileSync(SRC,'utf8');assert((src.split(LEG).length-1)===1,'legacy rng source lock');src=src.replace(LEG,ST);
  const cut=src.indexOf('async function main()');assert(cut>0,'main boundary');const prefix=src.slice(0,cut);
  const fakeFetch=async url=>{assert(String(url)==='https://api.sleeper.app/v1/players/nfl','unexpected fetch '+url);return{ok:true,status:200,json:async()=>structuredClone(fix)}};
  const expose=`\nreturn {loadMeta,buildPlayers,initRepl,rng,wpick,special,oppWeight,counts,slotAt,USER_SLOT,USER_PICKS,ACTIVE,addPick,pmeta,controlChoice};`;
  return new Function('require','fetch','structuredClone',prefix+expose)(require,fakeFetch,structuredClone);
}
function init(api,players,seed){const available=new Set(Object.keys(players)),rosters=Object.fromEntries(Array.from({length:10},(_,i)=>[i+1,[]])),picks=[],pm={};for(const[k,p]of Object.entries(players))pm[k]=api.pmeta(p);return{seed,r:api.rng(seed),available,rosters,picks,pm,nextPn:1}}
function clone(s){return{seed:s.seed,r:s.r.clone(),available:new Set(s.available),rosters:structuredClone(s.rosters),picks:structuredClone(s.picks),pm:structuredClone(s.pm),nextPn:s.nextPn}}
function opp(api,players,s,pn,stress='baseline'){const slot=api.slotAt(pn),name=api.ACTIVE[slot];assert(!!name,'manager missing slot '+slot);const c=api.counts(s.rosters[slot]),sp=api.special(s.r,name,c,pn);if(sp){s.rosters[slot].push({key:`__${sp}_${pn}`,name:sp,pos:sp});api.addPick(s.picks,s.pm,pn,slot,null,sp);return}const board=[...s.available].map(k=>players[k]).sort((a,b)=>a.panel-b.panel||a.adp-b.adp).slice(0,70);const w=board.map(p=>api.oppWeight(p,pn,c,name,stress)),ch=api.wpick(s.r,board,w);assert(ch&&s.available.has(ch.key),'invalid opponent pick '+pn);s.available.delete(ch.key);s.rosters[slot].push(ch);api.addPick(s.picks,s.pm,pn,slot,ch)}
function userMarket(api,players,s,pn){const ch=api.controlChoice(players,s.available,s.rosters[api.USER_SLOT],pn,'MARKET_ROSTER');assert(ch&&s.available.has(ch.key),'invalid market user pick '+pn);s.available.delete(ch.key);s.rosters[api.USER_SLOT].push(ch);api.addPick(s.picks,s.pm,pn,api.USER_SLOT,ch);return ch}
function advance(api,players,s,targetExclusive){for(let pn=s.nextPn;pn<targetExclusive;pn++){if(api.slotAt(pn)===api.USER_SLOT)userMarket(api,players,s,pn);else opp(api,players,s,pn);s.nextPn=pn+1}return s}
function legalEarly(api,s,p){const c=api.counts(s.rosters[api.USER_SLOT]);if(p.pos==='QB'&&c.QB>=1)return false;if(p.pos==='TE'&&c.TE>=1)return false;return true}
function frontier(api,players,s,pn){const avail=[...s.available].map(k=>players[k]).filter(Boolean).filter(p=>legalEarly(api,s,p));const byPanel=avail.slice().sort((a,b)=>a.panel-b.panel||a.adp-b.adp).slice(0,8),byAdp=avail.slice().sort((a,b)=>a.adp-b.adp||a.panel-b.panel).slice(0,8);const m=new Map([...byPanel,...byAdp].map(p=>[p.key,p]));if(pn===12){const b=avail.find(p=>String(p.name).toLowerCase()==='brock bowers');if(b)m.set(b.key,b)}return [...m.values()].sort((a,b)=>a.panel-b.panel||a.adp-b.adp)}
function force(api,s,p,pn){assert(s.nextPn===pn,'wrong treatment pn');assert(s.available.has(p.key),'candidate unavailable '+p.name);assert(legalEarly(api,s,p),'candidate illegal '+p.name);const before=s.r.snapshot();s.available.delete(p.key);s.rosters[api.USER_SLOT].push(p);api.addPick(s.picks,s.pm,pn,api.USER_SLOT,p);assert(stable(before)===stable(s.r.snapshot()),'treatment advanced RNG');s.nextPn=pn+1}
function finish(api,players,s){for(let pn=s.nextPn;pn<=150;pn++){if(api.slotAt(pn)===api.USER_SLOT)userMarket(api,players,s,pn);else opp(api,players,s,pn);s.nextPn=pn+1}return s}
function prefixView(s){return{picks:s.picks,available:[...s.available].sort(),userRoster:s.rosters[9].map(p=>p.key),rng:s.r.snapshot(),nextPn:s.nextPn}}
function branchRow(api,players,base,p,pn){const s=clone(base),prefix=prefixView(base),fp=sha(prefix);assert(sha(prefixView(s))===fp,'clone prefix mismatch');force(api,s,p,pn);finish(api,players,s);const mine=s.rosters[9].filter(p=>['QB','RB','WR','TE'].includes(p.pos));const c=api.counts(mine);assert(mine.length===15,'user skill roster '+mine.length);assert(c.QB>=1&&c.RB>=1&&c.WR>=2&&c.TE>=1,'starter infeasible');return{candidate:{key:p.key,name:p.name,pos:p.pos,panel:p.panel,adp:p.adp},prefix_fingerprint:fp,treatment_rng:prefix.rng,complete_picks:s.picks,user_roster:mine.map(x=>({key:x.key,name:x.name,pos:x.pos,panel:x.panel,adp:x.adp})),free_agent_ids:[...s.available].sort(),final_rng:s.r.snapshot(),complete_fingerprint:sha({picks:s.picks,fa:[...s.available].sort(),rng:s.r.snapshot()})}}
(async()=>{
  const fix=await fixture(),api=buildApi(fix);await api.loadMeta();const players=api.buildPlayers();assert(Object.keys(players).length>=225,'player pool '+Object.keys(players).length);api.initRepl(players);
  const seeds=[459271001,459271002],rows=[];
  for(const seed of seeds){for(const pn of[9,12]){const base=advance(api,players,init(api,players,seed),pn);const f=frontier(api,players,base,pn);assert(f.length>=6,'frontier '+pn);const fp=sha(prefixView(base));const a=f.map(p=>branchRow(api,players,base,p,pn)),b=f.slice().reverse().map(p=>branchRow(api,players,base,p,pn));const rb=new Map(b.map(x=>[x.candidate.key,x]));for(const x of a){const y=rb.get(x.candidate.key);assert(y&&x.complete_fingerprint===y.complete_fingerprint,'candidate order dependence '+pn+' '+x.candidate.name);assert(x.prefix_fingerprint===fp,'prefix changed '+pn)}rows.push({seed,treatment_pick:pn,prefix_policy:pn===12?'MARKET_ROSTER at 1.09':'none',continuation:'MARKET_ROSTER plumbing-only',prefix_fingerprint:fp,prefix_rng:base.r.snapshot(),prefix_picks:base.picks,frontier:f.map(p=>({key:p.key,name:p.name,pos:p.pos,panel:p.panel,adp:p.adp})),branches:a})}}
  const out={schema:1,status:'PASS',purpose:'causal plumbing only; NO outcome interpretation',kernel:'actual validated rc4.59 full-policy opponent kernel',metadata_fixture_players:Object.keys(fix).length,seeds,treatment_picks:[9,12],frontier_rule:'union top-8 selected-panel and top-8 Sleeper ADP; Bowers retained at 2.02 if legal',continuation:'MARKET_ROSTER only for plumbing gate; PairSum-LONG2 still required before strategic screen',invariants:['shared-prefix fingerprint','cloned RNG snapshot','treatment consumes zero outer RNG','candidate-order independence','complete deterministic replay','15-player skill roster','starter feasibility'],rows};fs.mkdirSync('counterfactual_2026',{recursive:true});fs.writeFileSync('counterfactual_2026/RC459_DECISION_COUNTERFACTUAL_PLUMBING_2026.json',JSON.stringify(out));console.log(JSON.stringify({status:'PASS',states:rows.length,branches:rows.reduce((n,x)=>n+x.branches.length,0),treatments:[9,12],seeds},null,2));
})().catch(e=>{console.error(e.stack||e);process.exit(2)});
