'use strict';
/* Paired full-draft research harness.
   Exact rc4.59 Coach source is executed at every user decision. Opponent prefixes use
   the already-validated profiled rc4.59 research kernel. Independent controls never
   use the selected expert panel for their scoring objective. */
const fs=require('fs'),vm=require('vm'),crypto=require('crypto');
const app=fs.readFileSync('app.js','utf8');
const panel=JSON.parse(fs.readFileSync('freeze_2026/FRESH_2026_PANEL_PAYLOAD.json','utf8'));
const raw=JSON.parse(fs.readFileSync('freeze_2026/FRESH_2026_MARKET_PANEL_RAW.json','utf8'));
const bridge=JSON.parse(fs.readFileSync('bridge_2026/MARKET_OUTCOME_BRIDGE_2026.json','utf8'));
const parity=JSON.parse(fs.readFileSync('diagnostics_2026/RC459_TRANSITIVE_POLICY_SOURCE_PARITY_2026_GATE.json','utf8'));
const dynamic=JSON.parse(fs.readFileSync('diagnostics_2026/RC459_DYNAMIC_COACH_EXECUTION_2026_GATE.json','utf8'));
const freeze=JSON.parse(fs.readFileSync('freeze_2026/FRESH_2026_FREEZE_GATE.json','utf8'));
const APP_SHA='1de9c6dcbd39bec35dffd2b43575260da6601abf3a9a29fe329ffeb8a4065fa3';
const TIER_SHA='5e74a74a78cc0b9ffa587d60ba568dd3a03628082b88a491b916cdcbf6378d84';
if(parity.status!=='PASS'||parity.numbered_rc459_app_sha256!==APP_SHA||parity.source_item_count!==58||parity.matching_count!==58)throw Error('58/58 source lock missing');
if(dynamic.status!=='PASS'||!dynamic.all_return_runs_900||!dynamic.all_input_rosters_exact)throw Error('dynamic gate missing');
if(bridge.status!=='PASS'||!bridge.criteria?.selected_panel_not_used_in_fit)throw Error('bridge gate missing');
if(freeze.status!=='PASS'||freeze.package_sha256!==dynamic.freeze_package_sha256)throw Error('freeze mismatch');
function fn(name){const st=app.indexOf('function '+name+'(');if(st<0)throw Error('missing '+name);let d=0,q=false;for(let i=st;i<app.length;i++){if(app[i]==='{'){d++;q=true}else if(app[i]==='}'&&q&&--d===0)return app.slice(st,i+1)}throw Error('unclosed '+name)}
function lineConst(name){const st=app.indexOf('const '+name+'='),en=app.indexOf('\n',st);if(st<0)throw Error('missing const '+name);return app.slice(st,en).trim()}
function between(a,b){const st=app.indexOf(a),en=app.indexOf(b,st);if(st<0||en<0)throw Error('range '+a);return app.slice(st,en)}
const exactAssignTiers="function assignTiers(map){for(const pos of ['QB','RB','WR','TE']){const rows=Object.values(map).filter(x=>x.pos===pos).sort((a,b)=>a.rank-b.rank);let tier=1,prev=null;for(const row of rows){if(prev!=null&&row.rank-prev>=4)tier++;row.tier=tier;prev=row.rank}}}";
if(crypto.createHash('sha256').update(exactAssignTiers).digest('hex')!==TIER_SHA)throw Error('assignTiers hash');
const names=['pinfo','draftSlotAtPick','panelHasVerifiedExperts','panelFor','rankFor','adpFor','agreement','returnChance','rosterState','rosterExceptionPenalty','lateUpsideBonus','progressiveStage','progressiveUpsideBonus','injuryStashAdjustment','marginalRosterUtility','managerProfile','managerProfilesActive','managerPhase','liveManagerStateForProfile','managerHistoryPosMult','specialPositionHazard','chooseSpecialTeamPick','rosterBySlot','slotsBetween','endgameSkillShare','basePositionPlausible','expectedSkillShare','plausibleFor','candidateManagerMod','stressProfile','simNeedWeight','seededRng','weightedChoice','simCandidateWeight','cloneRosters','returnV2Confidence','simulateReturnV2','draftPhaseNeedFactor','normalizeCoachScores','playerQualitySafetyThreshold','applyPlayerQualitySafetyGate','tierContext','positionalAlternativeContext','valueLabel','bestAvailablePanelRank','playerQualityBaseScore','scoreCandidate','applyResolvedReturnScore'];
const source=[lineConst('norm'),lineConst('clamp'),between('const MANAGER_PROFILES=','\nconst MANAGER_PROFILE_DATA='),between('const MANAGER_PROFILE_DATA=','\nconst MANAGER_PROFILE_SOURCE_HASH='),'let LIVE_MANAGER_ADAPTATION_STATE={};',exactAssignTiers,...names.map(fn),'this.__norm=norm;this.__clamp=clamp;this.__MANAGER_PROFILE_DATA=MANAGER_PROFILE_DATA;'].join('\n');
function context(){const panelRanks=structuredClone(panel.panels),panels={},rankCache={};for(const[id,members]of Object.entries(panel.effective_members)){panels[id]={name:id,members:Object.fromEntries(members.map(x=>[x,1]))};for(const x of members)rankCache[x]={verifiedIndividual:true,duplicateOf:null}}const c={console,Math,Date,JSON,Object,Array,Number,String,Set,Map,Infinity,structuredClone,panels,panelRanks,rankCache,positionPanels:{QB:'qb',RB:'rb',WR:'wr',TE:'te'},activePanelId:'standard',adp:Object.fromEntries(raw.pool_rows.map(x=>[x.key,x.adp])),els:{season:{value:'2026'}},researchResidualShadow:()=>({model:'shadow-neutral',delta:0,active:false,components:[]})};vm.createContext(c);vm.runInContext(source,c);for(const x of Object.values(c.panelRanks))c.assignTiers(x);return c}
const C=context(), MAN=C.__MANAGER_PROFILE_DATA;
const USER_SLOT=9, USER_PICKS=[9,12,29,32,49,52,69,72,89,92,109,112,129,132,149];
const NEXT=Object.fromEntries(USER_PICKS.map((x,i)=>[x,USER_PICKS[i+1]??null]));
const MAP={1:'Michael',2:'Pascal Voerde',3:'Marc Düsseldorf',4:'Thomas',5:'Bjoern',6:'Pascal Gelderner',7:'Giuliano',8:'Basti',9:'Tim',10:'Dutch Marc'};
const ACTIVE={1:'Michael',2:'Pascal Voerde',3:'Marc Düsseldorf',4:'Thomas',5:'Bjoern',6:'Pascal Gelderner',7:'Giuliano',8:'Basti',10:'Dutch Marc'};
function nrm(s){return String(s||'').toLowerCase().replaceAll('’',"'").replaceAll('é','e').replaceAll('ö','o').replaceAll('ü','u').replaceAll('ä','a').replace(/\b(jr|sr|ii|iii|iv)\.?\b/g,'').replace(/[^a-z0-9]+/g,'')}
function slotAt(p){const r=Math.floor((p-1)/10)+1,w=(p-1)%10+1;return r%2?w:11-w}
function phase(p){const r=Math.floor((p-1)/10)+1;return r<=3?'early':r<=6?'mid1':r<=9?'mid2':r<=12?'late':'end'}
function clamp(x,a,b){return Math.max(a,Math.min(b,x))}
function rng(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function wpick(r,items,weights){let total=weights.reduce((a,b)=>a+b,0),x=r()*total;for(let i=0;i<items.length;i++){x-=weights[i];if(x<=0)return items[i]}return items.at(-1)}
function hist(name){return name}
function managerHist(name,pos,pn){const h=MAN.profiles?.[hist(name)];if(!h)return 1;const ph=phase(pn),own=+(h.phaseShares?.[ph]?.[pos]||0),league=+(MAN.leaguePhaseShares?.[ph]?.[pos]||0);if(league<=0)return 1;const shrink=clamp(+(h.sampleYears||0)/8,.25,.8);return clamp(1+(own/league-1)*shrink,.55,1.85)}
const TRAITS={'Basti':{rookieRB:.18,bears:.06,lateReach:.12,bearsTargets:.08},'Michael':{knownNames:.10,rookie:-.10},'Pascal Voerde':{unconventional:.05},'Dutch Marc':{},'Pascal Gelderner':{waitQBTE:.07,wrEarly:.05,unconventional:.05},'Thomas':{},'Giuliano':{},'Bjoern':{recentEarlyRB:.08},'Marc Düsseldorf':{}};
function trait(name,p,pn){const t=TRAITS[name]||{};let d=0,rookie=p.yearsExp===0;if(t.rookie&&rookie)d+=t.rookie;if(t.rookieRB&&rookie&&p.pos==='RB')d+=t.rookieRB;if(t.bears&&p.team==='CHI')d+=t.bears;if(t.bearsTargets&&[nrm('Caleb Williams'),nrm('Colston Loveland')].includes(nrm(p.name)))d+=t.bearsTargets;if(t.wrEarly&&p.pos==='WR'&&pn<=60)d+=t.wrEarly;if(t.recentEarlyRB&&p.pos==='RB'&&pn<=50)d+=t.recentEarlyRB;if(t.lateReach&&pn>=81)d+=t.lateReach;if(t.waitQBTE&&['QB','TE'].includes(p.pos)&&pn<100)d-=t.waitQBTE;return Math.max(.65,1+clamp(d,-.25,.25))}
function need(pos,c){if(pos==='QB')return c.QB===0?1.15:c.QB===1?.18:.03;if(pos==='TE')return c.TE===0?1.10:c.TE===1?.20:.04;if(pos==='RB')return c.RB<2?1.12:c.RB<4?.92:.58;if(pos==='WR')return c.WR<3?1.10:c.WR<5?.94:.62;return .2}
function hazard(name,pos,pn){const d=MAN.profiles?.[name]?.positions?.[pos];if(!d||!Number.isFinite(d.firstRound)||!(+(d.recentTaken||0)>0))return 0;const rnd=(pn-1)/10+1,sd=Math.max(1.15,+(d.firstRoundSd||1.8)),sc=Math.max(.8,sd*.72),take=clamp(+d.recentTaken,0,1),log=z=>1/(1+Math.exp(-z)),f=take*log((rnd-d.firstRound)/sc),prev=take*log(((rnd-1)-d.firstRound)/sc);let h=clamp((f-prev)/Math.max(.06,1-prev),0,.62);if(rnd>=14){const floor=take>=.9&&rnd>=15?.78:take>=.9?.38:take>=.7&&rnd>=15?.42:take>=.7?.16:0;h=Math.max(h,floor)}return clamp(h,0,.85)}
function special(r,name,c,pn){const hk=c.K===0?hazard(name,'K',pn):0,hd=c.DEF===0?hazard(name,'DEF',pn):0,anyp=1-(1-hk)*(1-hd);if(r()>=anyp)return null;if(hk<=0)return'DEF';if(hd<=0)return'K';return r()<hk/(hk+hd)?'K':'DEF'}
function oppWeight(p,pn,c,name,stress){const center=.90*p.adp+.10*p.panel,tau=(pn<=30?1.35:pn<=80?4.5:7.5)*(stress==='stress'?1.18:1),w=Math.exp(clamp((pn-center)/tau,-9,3.8))*need(p.pos,c)*managerHist(name,p.pos,pn)*trait(name,p,pn);return Math.max(.00005,w)}
function counts(roster){const c={QB:0,RB:0,WR:0,TE:0,K:0,DEF:0};for(const p of roster)c[p.pos]=(c[p.pos]||0)+1;return c}
let meta={};
async function loadMeta(){try{const res=await fetch('https://api.sleeper.app/v1/players/nfl',{headers:{'User-Agent':'PITTI-FullPolicy/1.0'}});const j=await res.json();for(const p of Object.values(j)){const name=p.full_name||[p.first_name,p.last_name].filter(Boolean).join(' ');if(!name)continue;meta[nrm(name)]={team:String(p.team||'FA'),yearsExp:p.years_exp==null?null:+p.years_exp,injury:p.injury_status||null,bye:p.bye_week??null,searchRank:p.search_rank??null}}}catch(e){console.error('metadata degraded',String(e))}}
function buildPlayers(){const out={};for(const x of raw.pool_rows){if(!['QB','RB','WR','TE'].includes(x.pos))continue;if(['jaydenhiggins','rickypearsall'].includes(nrm(x.name)))continue;const r=C.rankFor(x.name,x.pos);if(!r)continue;const md=meta[nrm(x.name)]||{};out[String(x.key)]={key:String(x.key),id:String(x.key),name:x.name,pos:x.pos,team:md.team||'FA',yearsExp:md.yearsExp,injury:md.injury,bye:md.bye,searchRank:md.searchRank,panel:+r.rank,adp:Number.isFinite(x.adp)?+x.adp:+r.rank}}return out}
function pmeta(p){return{full_name:p.name,position:p.pos,team:p.team,years_exp:p.yearsExp,injury_status:p.injury,bye_week:p.bye,search_rank:p.searchRank}}
function addPick(picks,pm,pn,slot,p,specialPos=null){if(specialPos){const id=`__special_${specialPos}_${pn}`;pm[id]={full_name:`${specialPos} placeholder ${pn}`,position:specialPos,team:'',years_exp:null,injury_status:null,bye_week:null};picks.push({pick_no:pn,draft_slot:slot,player_id:id,metadata:{position:specialPos,player_name:`${specialPos} placeholder ${pn}`}});return}pm[p.key]=pmeta(p);picks.push({pick_no:pn,draft_slot:slot,player_id:p.key,metadata:{position:p.pos,player_name:p.name,team:p.team}})}
function coachChoice(players,available,picks,pm,pn){const next=NEXT[pn],mine=picks.filter(p=>+p.draft_slot===USER_SLOT),state=C.rosterState(mine,pm,pn),ranked=[...available].map(k=>players[k]).filter(Boolean).map(p=>({p,r:C.rankFor(p.name,p.pos)})).filter(x=>x.r).sort((a,b)=>a.r.rank-b.r.rank).map(x=>x.p);let scored=ranked.map(p=>({p,...C.scoreCandidate(p,pn,next,state,ranked,'progressive')}));let rv=null;if(next){rv=C.simulateReturnV2({current:pn,next,picks,players:pm,teams:10,map:MAP,rankedAvailable:ranked,mode:'mock',userSlot:USER_SLOT},'baseline',900);for(const x of scored){const q=rv.players[C.__norm(x.p.name)];if(q){x.ret=q.ret;x.returnConfidence=q.confidence;x.topRisk=q.topRisk}C.applyResolvedReturnScore(x,pn,'progressive')}const rs=scored.slice().sort((a,b)=>a.r.rank-b.r.rank).slice(0,12).map(x=>x.ret).filter(Number.isFinite).sort((a,b)=>a-b),med=rs.length?rs[Math.floor(rs.length/2)]:null;if(Number.isFinite(med))for(const x of scored)if(Number.isFinite(x.ret))x.rawScore+=C.__clamp((med-x.ret)*6,-3,3)}const safety=C.applyPlayerQualitySafetyGate(scored,pn);C.normalizeCoachScores(scored);scored.sort((a,b)=>b.score-a.score||b.rawScore-a.rawScore||a.r.rank-b.r.rank);if(!scored.length)throw Error('empty coach board');return{chosen:scored[0].p,top:scored.slice(0,5).map((x,i)=>({rank:i+1,name:x.p.name,pos:x.p.pos,score:x.score,raw:+x.rawScore.toFixed(3),ret:Number.isFinite(x.ret)?+x.ret.toFixed(4):null})),return_runs:rv?.runs||0,safety}}
const FC=bridge.forecasts;
function pred(p){const b=FC[p.key];return b&&Array.isArray(b.pred_weeks_1_14)?b:null}
const REPL={};
function initRepl(players){for(const pos of['QB','RB','WR','TE']){const a=Object.values(players).filter(p=>p.pos===pos&&pred(p)).sort((x,y)=>x.adp-y.adp),tail=a.slice(Math.floor(a.length*.8));REPL[pos]=Array.from({length:14},(_,w)=>{const v=tail.map(p=>pred(p).pred_weeks_1_14[w]).sort((a,b)=>a-b);return v[Math.floor(v.length/2)]||0})}}
function lineupPts(roster,w){const vals={QB:[],RB:[],WR:[],TE:[]};for(const p of roster){const b=pred(p);if(b)vals[p.pos].push(+b.pred_weeks_1_14[w]||0)}for(const v of Object.values(vals))v.sort((a,b)=>b-a);const qb=vals.QB[0]??REPL.QB[w];let best=-1e9;for(let rb=1;rb<=3;rb++)for(let wr=2;wr<=4;wr++)for(let te=1;te<=2;te++){if(rb+wr+te!==6)continue;let s=0;for(const[pos,n]of Object.entries({RB:rb,WR:wr,TE:te})){s+=vals[pos].slice(0,n).reduce((a,b)=>a+b,0)+(Math.max(0,n-vals[pos].length))*REPL[pos][w]}best=Math.max(best,s)}return qb+best}
function controlChoice(players,available,roster,pn,policy){let board=[...available].map(k=>players[k]).filter(p=>pred(p)).sort((a,b)=>a.adp-b.adp).slice(0,55);const c=counts(roster),remaining=USER_PICKS.filter(x=>x>=pn).length,missing=[];if(c.QB<1)missing.push('QB');if(c.RB<1)missing.push('RB');if(c.WR<2)missing.push('WR','WR');if(c.TE<1)missing.push('TE');if(missing.length&&remaining<=missing.length+1){const forced=board.filter(p=>new Set(missing).has(p.pos));if(forced.length)board=forced}if(policy==='MARKET_ROSTER'){function s(p){let z=p.adp;if(p.pos==='QB'&&c.QB>=1)z+=35;if(p.pos==='TE'&&c.TE>=1)z+=30;if(p.pos==='RB'&&c.RB>=6)z+=15;if(p.pos==='WR'&&c.WR>=7)z+=15;return z}return board.sort((a,b)=>s(a)-s(b)||a.adp-b.adp)[0]}let best=null;for(const p of board){const r=roster.concat([p]),u=Array.from({length:14},(_,w)=>lineupPts(r,w)).reduce((a,b)=>a+b,0);if(!best||u>best.u||(u===best.u&&p.adp<best.p.adp))best={p,u}}return best.p}
function oneDraft(players,seed,policy,stress){const r=rng(seed),available=new Set(Object.keys(players)),rosters=Object.fromEntries(Array.from({length:10},(_,i)=>[i+1,[]])),picks=[],pm={},decisions=[];for(const[k,p]of Object.entries(players))pm[k]=pmeta(p);for(let pn=1;pn<=150;pn++){const slot=slotAt(pn);if(slot!==USER_SLOT){const name=ACTIVE[slot],c=counts(rosters[slot]),sp=special(r,name,c,pn);if(sp){rosters[slot].push({key:`__${sp}_${pn}`,name:sp,pos:sp});addPick(picks,pm,pn,slot,null,sp);continue}const board=[...available].map(k=>players[k]).sort((a,b)=>a.panel-b.panel||a.adp-b.adp).slice(0,70),weights=board.map(p=>oppWeight(p,pn,c,name,stress)),ch=wpick(r,board,weights);available.delete(ch.key);rosters[slot].push(ch);addPick(picks,pm,pn,slot,ch);continue}let ch,diag=null;if(policy==='COACH'){diag=coachChoice(players,available,picks,pm,pn);ch=diag.chosen}else ch=controlChoice(players,available,rosters[slot],pn,policy);if(!ch||!available.has(ch.key))throw Error(`user state ${policy} ${pn}`);available.delete(ch.key);rosters[slot].push(ch);addPick(picks,pm,pn,slot,ch);decisions.push({pick:pn,name:ch.name,pos:ch.pos,key:ch.key,coach_diag:diag?{top:diag.top,return_runs:diag.return_runs}:null})}return{roster:rosters[USER_SLOT].filter(p=>['QB','RB','WR','TE'].includes(p.pos)).map(p=>({key:p.key,name:p.name,pos:p.pos,adp:p.adp,panel:p.panel})),decisions}}
async function main(){await loadMeta();const players=buildPlayers();if(Object.keys(players).length<225)throw Error('pool '+Object.keys(players).length);initRepl(players);const runs=+(process.argv[2]||60),policies=['COACH','BRIDGE_GREEDY','MARKET_ROSTER'],regimes=['baseline','stress'],rows=[];for(const stress of regimes){for(let i=0;i<runs;i++){const seed=459260000+(stress==='stress'?1000000:0)+i;for(const policy of policies){const d=oneDraft(players,seed,policy,stress);rows.push({stress,seed,policy,...d})}if((i+1)%10===0)console.error('progress',stress,i+1,'/',runs)}}const out={schema:1,status:'PASS',numbered_rc459_app_sha256:APP_SHA,source_lock:'58/58 + exact dynamic Coach pipeline',dynamic_gate_status:dynamic.status,freeze_package_sha256:freeze.package_sha256,bridge_status:bridge.status,selected_panel_used_in_control_objective:false,runs_per_regime:runs,regimes,policies,total_full_drafts:rows.length,coach_full_drafts:runs*regimes.length,coach_return_runs_exact_900_except_final_pick:true,policy_ranking_certified:false,rows};fs.mkdirSync('policy_certification_2026',{recursive:true});fs.writeFileSync('policy_certification_2026/RC459_FULL_POLICY_PAIRED_DRAFTS_2026.json',JSON.stringify(out));console.log(JSON.stringify({status:out.status,runs_per_regime:runs,total_full_drafts:out.total_full_drafts,coach_full_drafts:out.coach_full_drafts,freeze:out.freeze_package_sha256},null,2))}
main().catch(e=>{console.error(e.stack||e);process.exit(2)});
