'use strict';
/* Research-only roster-reality challenger.
   Preserve exact metadata-safe rc4.59 Coach/opponent/seed logic and the existing soft QB2/TE2
   opportunity-cost treatment, but make QB3+ and TE3+ inadmissible before PlayerQualitySafety.
   Rationale is empirical league reality: 2023-2025 had zero 3+ QB team-seasons; TE3 was rare,
   while the current research baseline drafts 2-5 QBs in every seed. No app/runtime change. */
const fs=require('fs'),crypto=require('crypto'),cp=require('child_process'),path=require('path');
const POLICY='research/rc459_full_policy_paired_2026.js',FULL='research/rc459_realistic_fullmock_tier_audit_2026.js';
const POLICY_BLOB='5c313bb54538139145761c3885d29f480e138b45',FULL_BLOB='c1f26da2877f9b01e25ea4926c03c398e7878876';
function gitBlob(s){const b=Buffer.from(s);return crypto.createHash('sha1').update(Buffer.from(`blob ${b.length}\0`)).update(b).digest('hex')}
const policy0=fs.readFileSync(POLICY,'utf8'),full0=fs.readFileSync(FULL,'utf8');if(gitBlob(policy0)!==POLICY_BLOB)throw Error('POLICY_DRIFT '+gitBlob(policy0));if(gitBlob(full0)!==FULL_BLOB)throw Error('FULL_DRIFT '+gitBlob(full0));
const metaRe=/let meta=\{\};\s*async function loadMeta\(\)\{[\s\S]*?\}\s*function buildPlayers\(\)\{[\s\S]*?\}\s*function pmeta/;if((policy0.match(new RegExp(metaRe.source,'g'))||[]).length!==1)throw Error('META_ANCHOR_DRIFT');
const safeMeta=`let meta={};
async function loadMeta(){const res=await fetch('https://api.sleeper.app/v1/players/nfl',{headers:{'User-Agent':'PITTI-FullPolicy/1.0'}});if(!res.ok)throw Error('metadata fetch '+res.status);const j=await res.json();meta={};for(const [sid,p] of Object.entries(j||{})){const name=p.full_name||[p.first_name,p.last_name].filter(Boolean).join(' ');if(!name)continue;const nk=nrm(name),position=String(p.position||p.fantasy_positions?.[0]||'').toUpperCase(),rec={sleeperId:String(sid),team:String(p.team||'FA'),yearsExp:p.years_exp==null?null:+p.years_exp,injury:p.injury_status||null,bye:p.bye_week??null,searchRank:p.search_rank??null,position};if(position)(meta[nk+'|'+position]??=[]).push(rec)}}
function buildPlayers(){const out={};for(const x of raw.pool_rows){if(!['QB','RB','WR','TE'].includes(x.pos))continue;if(['jaydenhiggins','rickypearsall'].includes(nrm(x.name)))continue;const r=C.rankFor(x.name,x.pos);if(!r)continue;const matches=meta[nrm(x.name)+'|'+String(x.pos).toUpperCase()]||[];if(matches.length>1)throw Error('AMBIGUOUS_POSITION_METADATA '+x.name+' '+x.pos);const md=matches[0]||{};if(nrm(x.name)==='justinjefferson'&&String(x.pos).toUpperCase()==='WR'&&(md.position!=='WR'||md.team!=='MIN'||md.sleeperId!=='6794'))throw Error('JUSTIN_JEFFERSON_WR_METADATA_NOT_RESOLVED');out[String(x.key)]={key:String(x.key),id:String(x.key),name:x.name,pos:x.pos,team:md.team||'FA',yearsExp:md.yearsExp,injury:md.injury,bye:md.bye,searchRank:md.searchRank,panel:+r.rank,adp:Number.isFinite(x.adp)?+x.adp:+r.rank}}return out}
function pmeta`;
let policy=policy0.replace(metaRe,safeMeta);if(policy===policy0)throw Error('META_PATCH_NOOP');
const scoreAnchor="let scored=ranked.map(p=>({p,...C.scoreCandidate(p,pn,next,state,ranked,'progressive')})).filter(x=>x.r),rv=null;";if(full0.split(scoreAnchor).length!==2)throw Error('SCORE_ANCHOR_DRIFT');
const guarded=`let scored=ranked.map(p=>({p,...C.scoreCandidate(p,pn,next,state,ranked,'progressive')})).filter(x=>x.r);\n  scored=scored.filter(x=>!((x.p.pos==='QB'||x.p.pos==='TE')&&Number(state.counts?.[x.p.pos]||0)>=2));\n  let rv=null;`;
let full=full0.replace(scoreAnchor,guarded);const shard=Number(process.env.PITTI_SHARD);if(!Number.isInteger(shard)||shard<0||shard>5)throw Error('PITTI_SHARD 0..5 required');const seedAnchor="const seeds=Array.from({length:60},(_,i)=>459710001+i),drafts=[];";if(full.split(seedAnchor).length!==2)throw Error('SEED_ANCHOR_DRIFT');const start=459710001+10*shard;full=full.replace(seedAnchor,`const seeds=Array.from({length:10},(_,i)=>${start}+i),drafts=[];`);
fs.writeFileSync(POLICY,policy);const tmp=path.join('/tmp',`pitti_meta_safe_qbte_cap2_${shard}.js`);fs.writeFileSync(tmp,full);let status=2;
try{const r=cp.spawnSync(process.execPath,[tmp],{stdio:'inherit',env:process.env});if(r.error)throw r.error;status=r.status??2;if(status===0){const src='simulation_2026/RC459_REALISTIC_FULLMOCK_TIER_AUDIT_2026.json';if(!fs.existsSync(src))throw Error('OUTPUT_MISSING');const x=JSON.parse(fs.readFileSync(src,'utf8'));if(x.status!=='PASS'||x.seeds!==10||x.drafts?.length!==10)throw Error('OUTPUT_INVALID');const expected=Array.from({length:10},(_,i)=>start+i);if(JSON.stringify(x.drafts.map(d=>d.seed))!==JSON.stringify(expected))throw Error('SEED_MISMATCH');for(const d of x.drafts){if(Number(d.position_counts?.QB||0)>2||Number(d.position_counts?.TE||0)>2)throw Error('CAP2_REALITY_GATE '+d.seed+' '+JSON.stringify(d.position_counts))}x.metadata_mapping='normalized-name + position, unique-match fail-closed';x.metadata_collision_source_bug_quarantined=true;x.qbte_repeat_policy='existing soft QB2/TE2 opportunity-cost treatment; hard user-roster reality cap only at QB3+/TE3+';x.production_mutation=false;const dst=`simulation_2026/RC459_META_SAFE_QBTE_CAP2_SHARD_${shard}_2026.json`;fs.renameSync(src,dst);fs.writeFileSync(dst,JSON.stringify(x));console.log(JSON.stringify({status:'PASS',shard,start,end:start+9,output:dst},null,2))}}finally{fs.writeFileSync(POLICY,policy0)}
if(status!==0)process.exit(status);
