'use strict';
/* Research-only shallow-league replacement diagnostic.
   Reads the FA-enriched causal artifact and measures roster-vs-actual-FA scarcity
   using frozen panel/ADP metadata only. This is NOT an outcome model. */
const fs=require('fs');
const IN='counterfactual_2026/RC459_CF_MARKET_FA_ENRICHED20_2026.json';
const OUT='counterfactual_2026/RC459_FA_REPLACEMENT_DIAGNOSTIC_2026.json';
const x=JSON.parse(fs.readFileSync(IN,'utf8'));if(x.status!=='PASS'||x.outcome_evaluated!==false)throw Error('input gate');
const pool=x.player_pool_snapshot||{},POS=['QB','RB','WR','TE'],MAX_START={QB:1,RB:3,WR:4,TE:2};
const finite=v=>Number.isFinite(+v),mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:null;
const quant=(a,q)=>{if(!a.length)return null;const v=[...a].sort((a,b)=>a-b),z=(v.length-1)*q,l=Math.floor(z),h=Math.ceil(z);return l===h?v[l]:v[l]*(h-z)+v[h]*(z-l)};
const rows=[];
for(const state of x.rows)for(const b of state.branches){const fa=b.free_agent_ids.map(id=>pool[id]).filter(Boolean),roster=b.user_roster||[];const by={};for(const pos of POS){const rr=roster.filter(p=>p.pos===pos&&finite(p.panel)).sort((a,b)=>a.panel-b.panel),ff=fa.filter(p=>p.pos===pos&&finite(p.panel)).sort((a,b)=>a.panel-b.panel),faAdp=fa.filter(p=>p.pos===pos&&finite(p.adp)).sort((a,b)=>a.adp-b.adp);const bestFA=ff[0]||null,startCap=MAX_START[pos],nonstart=rr.slice(startCap),worstRoster=rr.at(-1)||null,bestBench=nonstart[0]||null;by[pos]={roster_count:rr.length,max_simultaneous_starters:startCap,nonstartable_if_all_healthy:Math.max(0,rr.length-startCap),best_fa_panel_rank:bestFA?.panel??null,best_fa_name:bestFA?.name??null,best_fa_adp:faAdp[0]?.adp??null,best_bench_panel_rank:bestBench?.panel??null,worst_roster_panel_rank:worstRoster?.panel??null,worst_roster_minus_best_fa_panel:(worstRoster&&bestFA)?worstRoster.panel-bestFA.panel:null,best_bench_minus_best_fa_panel:(bestBench&&bestFA)?bestBench.panel-bestFA.panel:null,fa_top5_panel:ff.slice(0,5).map(p=>({name:p.name,panel:p.panel,adp:p.adp}))}}
rows.push({seed:state.seed,treatment_pick:state.treatment_pick,candidate:b.candidate,positions:by})}
const summary={};for(const pos of POS){const z=rows.map(r=>r.positions[pos]);const vals=k=>z.map(v=>v[k]).filter(finite).map(Number);summary[pos]={branches:z.length,mean_roster_count:mean(vals('roster_count')),mean_nonstartable_if_all_healthy:mean(vals('nonstartable_if_all_healthy')),best_fa_panel_rank:{mean:mean(vals('best_fa_panel_rank')),p10:quant(vals('best_fa_panel_rank'),.1),median:quant(vals('best_fa_panel_rank'),.5),p90:quant(vals('best_fa_panel_rank'),.9)},best_fa_adp:{mean:mean(vals('best_fa_adp')),median:quant(vals('best_fa_adp'),.5)},worst_roster_minus_best_fa_panel:{mean:mean(vals('worst_roster_minus_best_fa_panel')),p10:quant(vals('worst_roster_minus_best_fa_panel'),.1),median:quant(vals('worst_roster_minus_best_fa_panel'),.5),p90:quant(vals('worst_roster_minus_best_fa_panel'),.9)},best_bench_minus_best_fa_panel:{mean:mean(vals('best_bench_minus_best_fa_panel')),median:quant(vals('best_bench_minus_best_fa_panel'),.5)}}}
const out={schema:1,status:'PASS',research_only:true,outcome_model:false,interpretation_guard:'Panel/ADP scarcity diagnostic only. Negative roster-minus-FA gap means drafted player has better (lower) panel rank than best actual FA; does not imply equivalent weekly utility or title value.',input_seed_family:x.seed_family,input_states:x.rows.length,branches:rows.length,max_simultaneous_starters:MAX_START,summary,rows};fs.writeFileSync(OUT,JSON.stringify(out,null,2));console.log(JSON.stringify({status:'PASS',branches:rows.length,summary,output:OUT},null,2));