'use strict';
/* Research-only audit of the ACTUAL rc4.59 Coach under verified league geometry.
   Purpose: answer whether current Companion recommendations themselves violate the
   verified reality/tier-first contract. No recommendation is changed here.
   Opponents use the validated full-policy kernel plus the frozen Aug-22 Sleeper
   Half-PPR anchors where available. User choices execute exact rc4.59 score/
   Return-v2/safety logic. Raw decision rows are persisted before interpretation. */
const fs=require('fs'),crypto=require('crypto');
const CORE='research/rc459_decision_counterfactual_screen_2026.js';
const EXPECT='8cd71b5d01af8fe0f03ab0ff9ee3573486d4b5c3';
const raw=fs.readFileSync(CORE,'utf8'),buf=Buffer.from(raw),blob=crypto.createHash('sha1').update(Buffer.from(`blob ${buf.length}\0`)).update(buf).digest('hex');
if(blob!==EXPECT)throw Error('FULLMOCK_CORE_DRIFT '+blob);
const main=raw.indexOf('(async()=>');if(main<0)throw Error('main boundary');
const exp=`\nreturn {getFixture,apiFrom,init,clone,stable,sha,ok};`;
const H=new Function('require','fetch','structuredClone',raw.slice(0,main)+exp)(require,fetch,structuredClone);
const M=JSON.parse(fs.readFileSync('research/SLEEPER_HALF_PPR_MARKET_ANCHORS_2026-08-23.json','utf8'));
if(M.source?.platform!=='Sleeper'||M.source?.scoring!=='Half PPR'||M.source?.updated!=='2026-08-22')throw Error('market provenance');
const market=M.adp,controls9=new Set(M.strategy_exclusions?.['1.09_major_reach_controls']||[]),controls12=new Set(M.strategy_exclusions?.['2.02_major_reach_controls']||[]);
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const SUPERIOR=new Set(['Jaxon Smith-Njigba','Amon-Ra St. Brown','Jonathan Taylor']);
const CORE_TURN=new Set(['CeeDee Lamb','James Cook III','Justin Jefferson','Ashton Jeanty']);
const NEXT_TURN=new Set(["De'Von Achane",'Saquon Barkley','Chase Brown','Omarion Hampton','Kenneth Walker III','Brock Bowers']);
const FIRSTTURN_ALL=new Set([...SUPERIOR,...CORE_TURN,...NEXT_TURN,'Christian McCaffrey']);
function installCurrentMarketOpponent(api){const old=api.oppWeight;api.oppWeight=(p,pn,c,name,stress)=>{const m=market[p.name];if(!Number.isFinite(m))return old(p,pn,c,name,stress);const oldCenter=.90*p.adp+.10*p.panel,tau=(pn<=30?2.4:pn<=80?4.5:7.5)*(stress==='stress'?1.18:1),oldMk=Math.exp(clamp((pn-oldCenter)/tau,-9,3.8)),nonMk=Math.max(.00005,old(p,pn,c,name,stress))/Math.max(.00005,oldMk),newMk=Math.exp(clamp((pn-m)/tau,-9,3.8));return Math.max(.00005,newMk*nonMk)}}
function opponent(api,players,s,pn,stress='baseline'){const slot=api.slotAt(pn),name=api.ACTIVE[slot];H.ok(name,'missing manager '+slot);const c=api.counts(s.rosters[slot]),sp=api.special(s.r,name,c,pn);if(sp){const ph={key:`__${sp}_${pn}`,name:sp,pos:sp};s.rosters[slot].push(ph);api.addPick(s.picks,s.pm,pn,slot,null,sp);return ph}const board=[...s.available].map(k=>players[k]).filter(Boolean).sort((a,b)=>a.panel-b.panel||a.adp-b.adp).slice(0,70),w=board.map(p=>api.oppWeight(p,pn,c,name,stress)),ch=api.wpick(s.r,board,w);H.ok(ch&&s.available.has(ch.key),'opponent '+pn);s.available.delete(ch.key);s.rosters[slot].push(ch);api.addPick(s.picks,s.pm,pn,slot,ch);return ch}
function coachDecision(api,players,s,pn){const C=api.C,next=api.NEXT[pn],mine=s.picks.filter(p=>+p.draft_slot===api.USER_SLOT),state=C.rosterState(mine,s.pm,pn),ranked=[...s.available].map(k=>players[k]).filter(Boolean).map(p=>({p,r:C.rankFor(p.name,p.pos)})).filter(x=>x.r).sort((a,b)=>a.r.rank-b.r.rank||(a.p.searchRank||9999)-(b.p.searchRank||9999)).map(x=>x.p);let scored=ranked.map(p=>({p,...C.scoreCandidate(p,pn,next,state,ranked,'progressive')})).filter(x=>x.r),rv=null;if(next){rv=C.simulateReturnV2({current:pn,next,picks:s.picks,players:s.pm,teams:10,map:api.MAP,rankedAvailable:ranked,mode:'mock',userSlot:api.USER_SLOT},'baseline',900);for(const x of scored){const q=rv?.players?.[C.__norm(x.p.name)];if(q){x.ret=q.ret;x.returnConfidence=q.confidence;x.topRisk=q.topRisk}C.applyResolvedReturnScore(x,pn,'progressive')}}const boardTop=scored.slice().sort((x,y)=>x.r.rank-y.r.rank).slice(0,12).filter(x=>x.ret!=null),rets=boardTop.map(x=>x.ret).sort((a,b)=>a-b),med=rets.length?rets[Math.floor(rets.length/2)]:null;if(med!=null)for(const x of scored){if(x.ret==null)continue;x.rawScore+=C.__clamp((med-x.ret)*6,-3,3)}const safety=C.applyPlayerQualitySafetyGate(scored,pn);C.normalizeCoachScores(scored);scored.sort((a,b)=>b.score-a.score||b.rawScore-a.rawScore||a.r.rank-b.r.rank);H.ok(scored.length,'empty Coach '+pn);const top=scored.slice(0,10).map(x=>({name:x.p.name,pos:x.p.pos,panel:+x.r.rank,adp:Number.isFinite(x.a)?+x.a:null,score:x.score,raw:+x.rawScore.toFixed(3),ret:Number.isFinite(x.ret)?+x.ret.toFixed(4):null,tier:x.r.tier??null,reasons:x.reasons?.slice()||[]}));return{chosen:scored[0].p,chosenRow:scored[0],top,safety,medianReturn:med,state,ranked}}
function userPick(api,players,s,pn){const before=s.r.snapshot(),d=coachDecision(api,players,s,pn);H.ok(H.stable(before)===H.stable(s.r.snapshot()),'Coach decision advanced outer RNG '+pn);const p=d.chosen;H.ok(p&&s.available.has(p.key),'user '+pn);const availableBefore=[...s.available].map(k=>players[k]).filter(Boolean);const superiorAvail=availableBefore.filter(x=>SUPERIOR.has(x.name)).map(x=>x.name),coreAvail=availableBefore.filter(x=>CORE_TURN.has(x.name)).map(x=>x.name),firstAvail=availableBefore.filter(x=>FIRSTTURN_ALL.has(x.name)).map(x=>x.name);const flags=[];if(pn===9){if(controls9.has(p.name))flags.push('PICK9_MAJOR_REACH_CONTROL');if(superiorAvail.length&&!SUPERIOR.has(p.name))flags.push('SUPERIOR_FALLER_BYPASS');if(!superiorAvail.length&&coreAvail.length&&!CORE_TURN.has(p.name)&&!NEXT_TURN.has(p.name)&&p.name!=='Christian McCaffrey')flags.push('PICK9_OUTSIDE_REALISTIC_CLUSTER')}if(pn===12&&controls12.has(p.name))flags.push('PICK12_MAJOR_REACH_CONTROL');const bestPanel=d.top.reduce((m,x)=>Math.min(m,x.panel),Infinity),panelGap=Number.isFinite(bestPanel)?d.chosenRow.r.rank-bestPanel:null;if(Number.isFinite(panelGap)&&panelGap>=api.C.playerQualitySafetyThreshold(pn))flags.push('LARGE_PANEL_GAP_LEADER');s.available.delete(p.key);s.rosters[9].push(p);api.addPick(s.picks,s.pm,pn,9,p);return{pick:pn,name:p.name,pos:p.pos,panel:+d.chosenRow.r.rank,adp:Number.isFinite(d.chosenRow.a)?+d.chosenRow.a:null,ret:Number.isFinite(d.chosenRow.ret)?+d.chosenRow.ret:null,score:d.chosenRow.score,raw:+d.chosenRow.rawScore.toFixed(3),safety:d.safety,median_return:d.medianReturn,flags,superior_available:superiorAvail,core_available:coreAvail,firstturn_available:firstAvail,top:d.top}}
function runDraft(api,players,seed){const s=H.init(api,players,seed),decisions=[];for(let pn=1;pn<=150;pn++){if(api.slotAt(pn)===9)decisions.push(userPick(api,players,s,pn));else opponent(api,players,s,pn);s.nextPn=pn+1}const mine=s.rosters[9].filter(p=>['QB','RB','WR','TE'].includes(p.pos)),c=api.counts(mine);H.ok(mine.length===15,'user roster length');H.ok(c.QB>=1&&c.RB>=1&&c.WR>=2&&c.TE>=1,'starter feasibility');return{seed,decisions,user_roster:mine.map(p=>({name:p.name,pos:p.pos,panel:p.panel,adp:p.adp})),position_counts:c,free_agent_ids:[...s.available].sort(),complete_fingerprint:H.sha({picks:s.picks,fa:[...s.available].sort(),rng:s.r.snapshot()})}}
function summarize(rows){const byPick={};for(const r of rows)for(const d of r.decisions){const x=byPick[d.pick]??={n:0,choices:{},flags:{},mean_panel_gap:0};x.n++;x.choices[d.name]=(x.choices[d.name]||0)+1;for(const f of d.flags)x.flags[f]=(x.flags[f]||0)+1;const gap=d.top.length?d.panel-Math.min(...d.top.map(z=>z.panel)):0;x.mean_panel_gap+=gap}for(const x of Object.values(byPick))x.mean_panel_gap/=x.n;const first9=byPick[9],first12=byPick[12];return{by_pick:byPick,first_turn:{pick9:first9,pick12:first12},all_flags:Object.values(byPick).reduce((o,x)=>(Object.entries(x.flags).forEach(([k,v])=>o[k]=(o[k]||0)+v),o),{})}}
(async()=>{const fixture=await H.getFixture(),api=H.apiFrom(fixture);await api.loadMeta();installCurrentMarketOpponent(api);const players=api.buildPlayers();H.ok(Object.keys(players).length>=225,'pool');api.initRepl(players);const seeds=Array.from({length:60},(_,i)=>459710001+i),drafts=[];for(let i=0;i<seeds.length;i++){drafts.push(runDraft(api,players,seeds[i]));if((i+1)%10===0)console.log('progress',i+1,'/',seeds.length)}const summary=summarize(drafts);const out={schema:1,status:'PASS',research_only:true,production_mutation:false,app_policy:'exact rc4.59 progressive Coach score + Return-v2 900 + board-relative urgency + PlayerQualitySafetyGate',opponent_kernel:'validated rc4.59 full-policy kernel with frozen 2026-08-22 Sleeper Half-PPR anchors where available',market_provenance:M.source,seeds:seeds.length,seed_family:'459710xxx fresh',tier_diagnostic_contract:{superior_faller:[...SUPERIOR],core_turn:[...CORE_TURN],next_turn:[...NEXT_TURN],cmc:'conditional health/decline review',rule:'diagnostic only; no scalar tier score and no production forcing'},summary,drafts};fs.mkdirSync('simulation_2026',{recursive:true});const p='simulation_2026/RC459_REALISTIC_FULLMOCK_TIER_AUDIT_2026.json';fs.writeFileSync(p,JSON.stringify(out));console.log(JSON.stringify({status:'PASS',drafts:drafts.length,all_flags:summary.all_flags,pick9:summary.first_turn.pick9,pick12:summary.first_turn.pick12,output:p},null,2))})().catch(e=>{console.error(e.stack||e);process.exit(2)});
