'use strict';
/* Verified-current-market 1.09 -> Dutch 1.10/2.01 -> 2.02 pair harness.
   PRIMARY research only: current Sleeper-derived Half-PPR availability; verified geometry;
   no QB/reach controls; identical continuation; independent bridge/startability + actual-FA lenses.
   Does NOT change production strategy. */
const fs=require('fs'),crypto=require('crypto');
const CORE='research/rc459_decision_counterfactual_screen_2026.js';
const EXPECT='8cd71b5d01af8fe0f03ab0ff9ee3573486d4b5c3';
const raw=fs.readFileSync(CORE,'utf8'),buf=Buffer.from(raw),blob=crypto.createHash('sha1').update(Buffer.from(`blob ${buf.length}\0`)).update(buf).digest('hex');
if(blob!==EXPECT)throw Error('PAIR_CURRENT_CORE_DRIFT '+blob);
const main=raw.indexOf('(async()=>');if(main<0)throw Error('main boundary');
const exp=`\nreturn {getFixture,apiFrom,init,clone,advance,earlyLegal,prefixData,force,finish,stable,sha,ok};`;
const C=new Function('require','fetch','structuredClone',raw.slice(0,main)+exp)(require,fetch,structuredClone);
const M=JSON.parse(fs.readFileSync('research/SLEEPER_HALF_PPR_MARKET_ANCHORS_2026-08-23.json','utf8'));
if(M.source?.platform!=='Sleeper'||M.source?.scoring!=='Half PPR'||M.source?.updated!=='2026-08-22')throw Error('market provenance');
const market=M.adp, control9=new Set(M.strategy_exclusions?.['1.09_major_reach_controls']||[]),control12=new Set(M.strategy_exclusions?.['2.02_major_reach_controls']||[]);
const bridge=JSON.parse(fs.readFileSync('bridge_2026/MARKET_OUTCOME_BRIDGE_2026.json','utf8'));if(bridge.status!=='PASS')throw Error('bridge');
const FC=bridge.forecasts;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function installCurrentMarketOpponent(api){const old=api.oppWeight;api.oppWeight=(p,pn,c,name,stress)=>{const m=market[p.name];if(pn>32||!Number.isFinite(m))return old(p,pn,c,name,stress);const oldCenter=.90*p.adp+.10*p.panel,tau=(pn<=30?2.4:4.5)*(stress==='stress'?1.18:1),oldMk=Math.exp(clamp((pn-oldCenter)/tau,-9,3.8)),nonMk=Math.max(.00005,old(p,pn,c,name,stress))/Math.max(.00005,oldMk),newMk=Math.exp(clamp((pn-m)/tau,-9,3.8));return Math.max(.00005,newMk*nonMk)}}
const pred=p=>FC[p?.key]&&Array.isArray(FC[p.key].pred_weeks_1_14)?FC[p.key].pred_weeks_1_14.map(Number):null;
function lineup(roster,w){const v={QB:[],RB:[],WR:[],TE:[]};for(const p of roster){const q=pred(p);if(q&&Number.isFinite(q[w]))v[p.pos]?.push(q[w])}for(const a of Object.values(v))a.sort((a,b)=>b-a);if(!v.QB.length)return null;let best=-Infinity;/* exact verified topology: QB1 + RB1-3 + WR2-4 + TE1-2, six skill slots */for(let rb=1;rb<=3;rb++)for(let wr=2;wr<=4;wr++)for(let te=1;te<=2;te++){if(rb+wr+te!==6)continue;if(v.RB.length<rb||v.WR.length<wr||v.TE.length<te)continue;const s=v.QB[0]+v.RB.slice(0,rb).reduce((a,b)=>a+b,0)+v.WR.slice(0,wr).reduce((a,b)=>a+b,0)+v.TE.slice(0,te).reduce((a,b)=>a+b,0);if(s>best)best=s}return Number.isFinite(best)?best:null}
function seasonUtility(roster){let s=0,weeks=0;for(let w=0;w<14;w++){const x=lineup(roster,w);if(Number.isFinite(x)){s+=x;weeks++}}return weeks===14?s:null}
function bestFaByPos(fa,players,pos){let best=null,bestSum=-Infinity;for(const id of fa){const p=players[id];if(!p||p.pos!==pos)continue;const q=pred(p);if(!q)continue;const s=q.reduce((a,b)=>a+(Number.isFinite(b)?b:0),0);if(s>bestSum){best=p;bestSum=s}}return best}
function actualFaMarginal(roster,fa,players){const base=seasonUtility(roster);if(!Number.isFinite(base))return null;const rows=[];for(let i=0;i<roster.length;i++){const p=roster[i];if(!['QB','RB','WR','TE'].includes(p.pos))continue;const r=bestFaByPos(fa,players,p.pos);if(!r)continue;const repl=roster.slice();repl[i]=r;const u=seasonUtility(repl);if(Number.isFinite(u))rows.push({player:p.name,pos:p.pos,replacement:r.name,delta:base-u})}rows.sort((a,b)=>a.delta-b.delta);return{base,weakest:rows.slice(0,5),weakest3_mean:rows.length?rows.slice(0,Math.min(3,rows.length)).reduce((a,x)=>a+x.delta,0)/Math.min(3,rows.length):null}}
const seeds=Array.from({length:80},(_,i)=>459601001+i), pick9Max=14.0,pick12Max=24.5, skill9=new Set(['RB','WR']),skill12=new Set(['RB','WR','TE']);
const meta=p=>({key:p.key,name:p.name,pos:p.pos,panel:+p.panel,market:market[p.name]??null});
(async()=>{const fix=await C.getFixture(),api=C.apiFrom(fix);await api.loadMeta();installCurrentMarketOpponent(api);const players=api.buildPlayers();C.ok(Object.keys(players).length>=225,'pool');api.initRepl(players);const states=[];let branchesN=0;
for(const seed of seeds){const pre=C.advance(api,players,C.init(api,players,seed),9,'MARKET_NEUTRAL');const c9s=[...pre.available].map(k=>players[k]).filter(Boolean).filter(p=>skill9.has(p.pos)&&Number.isFinite(market[p.name])&&market[p.name]<=pick9Max&&!control9.has(p.name)).sort((a,b)=>market[a.name]-market[b.name]);if(!c9s.length)continue;for(const c9 of c9s){const s12=C.clone(pre);C.force(api,s12,c9,9);C.advance(api,players,s12,12,'MARKET_NEUTRAL');const dutch=s12.picks.filter(x=>[10,11].includes(+x.pick_no)).map(x=>x.metadata?.player_name);C.ok(dutch.length===2,'Dutch 10/11');const frontier=[...s12.available].map(k=>players[k]).filter(Boolean).filter(p=>C.earlyLegal(api,s12,p)&&skill12.has(p.pos)&&Number.isFinite(market[p.name])&&market[p.name]<=pick12Max&&!control12.has(p.name)).sort((a,b)=>market[a.name]-market[b.name]);if(!frontier.length)continue;const branches=[];const prefix=C.sha(C.prefixData(s12));for(const c12 of frontier){const ch=C.clone(s12);C.ok(C.sha(C.prefixData(ch))===prefix,'prefix');C.force(api,ch,c12,12);const fin=C.finish(api,players,ch,'MARKET_NEUTRAL');const roster=fin.mine.filter(p=>['QB','RB','WR','TE'].includes(p.pos)),fa=[...ch.available].sort();const util=seasonUtility(roster),fam=actualFaMarginal(roster,fa,players);C.ok(Number.isFinite(util),'utility '+c9.name+' '+c12.name);branches.push({pair:[c9.name,c12.name],construction:c9.pos+'->'+c12.pos,pick9:meta(c9),pick12:meta(c12),dutch_10_11:dutch,panel_pair_sum:c9.panel+c12.panel,independent_w1_14_lineup_utility:util,actual_fa_marginal:fam,user_roster:roster.map(meta),free_agent_ids:fa});branchesN++}states.push({seed,pick9:meta(c9),dutch_10_11:dutch,frontier_2_02:frontier.map(meta),branches})}}
C.ok(states.length>=250,'states '+states.length);C.ok(branchesN>=1500,'branches '+branchesN);
/* Pairwise directional comparisons only; no scalar winner. Same seed is required for opposite sequence. */
const seqs=[['James Cook III','Justin Jefferson'],['CeeDee Lamb','Justin Jefferson'],['Ashton Jeanty','Justin Jefferson'],['Saquon Barkley','Justin Jefferson'],["De'Von Achane",'Justin Jefferson']];
const comparisons=[];for(const [a,b] of seqs){let n=0,ab=0,ba=0,tie=0,panelAB=0,panelBA=0;for(const seed of seeds){const sab=states.find(s=>s.seed===seed&&s.pick9.name===a)?.branches.find(x=>x.pick12.name===b);const sba=states.find(s=>s.seed===seed&&s.pick9.name===b)?.branches.find(x=>x.pick12.name===a);if(!sab||!sba)continue;n++;const d=sab.independent_w1_14_lineup_utility-sba.independent_w1_14_lineup_utility;if(d>1e-9)ab++;else if(d< -1e-9)ba++;else tie++;if(sab.panel_pair_sum<sba.panel_pair_sum)panelAB++;else if(sba.panel_pair_sum<sab.panel_pair_sum)panelBA++}comparisons.push({A:a,B:b,common_seeds:n,independent_utility:{A_then_B_wins:ab,B_then_A_wins:ba,ties:tie,A_then_B_win_rate:n?ab/n:null},selected_panel_pair_rank:{A_then_B_better:panelAB,B_then_A_better:panelBA}})}
const out={schema:1,status:'PASS',strategy_certified:false,raw_pair_harness:true,market_provenance:M.source,market_tau:2.4,seeds:seeds.length,states:states.length,branches:branchesN,pick9_market_max:pick9Max,pick12_market_max:pick12Max,controls_excluded:{pick9:[...control9],pick12:[...control12]},comparisons,states_data:states};fs.mkdirSync('counterfactual_2026',{recursive:true});const p='counterfactual_2026/RC459_VERIFIED_CURRENT_MARKET_PAIRS_2026.json';fs.writeFileSync(p,JSON.stringify(out));console.log(JSON.stringify({status:'PASS',states:states.length,branches:branchesN,comparisons,output:p},null,2))})().catch(e=>{console.error(e.stack||e);process.exit(2)});