'use strict';
/* RAW causal screen on the actual validated rc4.59 full-policy kernel.
   No downstream outcome evaluator is called here. It forces each outcome-blind
   quality/market-plausible candidate at 1.09 or 2.02 and completes the draft under
   two frozen continuations: MARKET_NEUTRAL and exact screened PAIRSUM_LONG2. */
const fs=require('fs'),crypto=require('crypto');
const SRC='research/rc459_full_policy_paired_2026.js';
const LEG="function rng(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}";
const ST="function rng(seedOrState){let a=(typeof seedOrState==='object'?seedOrState.a:seedOrState)>>>0;let draws=(typeof seedOrState==='object'?(seedOrState.draws||0):0)>>>0;const r=function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;draws++;return((t^t>>>14)>>>0)/4294967296};r.snapshot=()=>({a:a>>>0,draws});r.clone=()=>rng(r.snapshot());return r}";
function stable(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(v instanceof Set)return stable([...v].sort());if(Array.isArray(v))return '['+v.map(stable).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}'}
function sha(v){return crypto.createHash('sha256').update(typeof v==='string'?v:stable(v)).digest('hex')}
function ok(x,m){if(!x)throw Error('CF_SCREEN_INVARIANT: '+m)}
async function getFixture(){const r=await fetch('https://api.sleeper.app/v1/players/nfl',{headers:{'User-Agent':'PITTI-CF-Screen/1.0'}});if(!r.ok)throw Error('Sleeper '+r.status);const j=await r.json();ok(Object.keys(j||{}).length>1000,'fixture');return j}
function apiFrom(fix){let src=fs.readFileSync(SRC,'utf8');ok(src.split(LEG).length-1===1,'rng source lock');src=src.replace(LEG,ST);const cut=src.indexOf('async function main()');ok(cut>0,'main boundary');const fake=async url=>{ok(String(url)==='https://api.sleeper.app/v1/players/nfl','unexpected fetch');return{ok:true,status:200,json:async()=>structuredClone(fix)}};const ret=`\nreturn {loadMeta,buildPlayers,initRepl,rng,wpick,special,oppWeight,counts,slotAt,USER_SLOT,USER_PICKS,NEXT,ACTIVE,MAP,addPick,pmeta,controlChoice,C};`;return new Function('require','fetch','structuredClone',src.slice(0,cut)+ret)(require,fake,structuredClone)}
function init(api,players,seed){const available=new Set(Object.keys(players)),rosters=Object.fromEntries(Array.from({length:10},(_,i)=>[i+1,[]])),picks=[],pm={};for(const[k,p]of Object.entries(players))pm[k]=api.pmeta(p);return{r:api.rng(seed),available,rosters,picks,pm,nextPn:1,seed}}
function clone(s){return{r:s.r.clone(),available:new Set(s.available),rosters:structuredClone(s.rosters),picks:structuredClone(s.picks),pm:structuredClone(s.pm),nextPn:s.nextPn,seed:s.seed}}
function opponent(api,players,s,pn,stress='baseline'){const slot=api.slotAt(pn),name=api.ACTIVE[slot];ok(name,'missing manager '+slot);const c=api.counts(s.rosters[slot]),sp=api.special(s.r,name,c,pn);if(sp){s.rosters[slot].push({key:`__${sp}_${pn}`,name:sp,pos:sp});api.addPick(s.picks,s.pm,pn,slot,null,sp);return}const board=[...s.available].map(k=>players[k]).sort((a,b)=>a.panel-b.panel||a.adp-b.adp).slice(0,70),w=board.map(p=>api.oppWeight(p,pn,c,name,stress)),ch=api.wpick(s.r,board,w);ok(ch&&s.available.has(ch.key),'opponent '+pn);s.available.delete(ch.key);s.rosters[slot].push(ch);api.addPick(s.picks,s.pm,pn,slot,ch)}
function marketChoice(api,players,s,pn){return api.controlChoice(players,s.available,s.rosters[api.USER_SLOT],pn,'MARKET_ROSTER')}
function priorPos(s,pos){return s.picks.filter(x=>+x.draft_slot===9&&String(x.metadata?.position||'').toUpperCase()===pos).length}
function pairSumChoice(api,players,s,pn){
 const C=api.C,next=api.NEXT[pn],mine=s.picks.filter(p=>+p.draft_slot===api.USER_SLOT),state=C.rosterState(mine,s.pm,pn),ranked=[...s.available].map(k=>players[k]).filter(Boolean).map(p=>({p,r:C.rankFor(p.name,p.pos)})).filter(x=>x.r).sort((a,b)=>a.r.rank-b.r.rank).map(x=>x.p);
 const pp=pos=>priorPos(s,pos),qb=pp('QB'),te=pp('TE');let coachPool=ranked.filter(p=>!(p.pos==='QB'&&qb>=1)&&!(p.pos==='TE'&&te>=1));const starterMissing=['QB','RB','WR','TE'].filter(pos=>pp(pos)===0),remainingOwn=api.USER_PICKS.filter(x=>x>=pn).length;if(starterMissing.length&&remainingOwn<=starterMissing.length){const f=coachPool.filter(p=>starterMissing.includes(p.pos));if(f.length)coachPool=f}if(!coachPool.length)coachPool=ranked;
 let scored=coachPool.map(p=>({p,...C.scoreCandidate(p,pn,next,state,ranked,'progressive')})),rv=null;if(next){rv=C.simulateReturnV2({current:pn,next,picks:s.picks,players:s.pm,teams:10,map:api.MAP,rankedAvailable:ranked,mode:'mock',userSlot:api.USER_SLOT},'baseline',900);for(const x of scored){const q=rv.players[C.__norm(x.p.name)];if(q){x.ret=q.ret;x.returnConfidence=q.confidence;x.topRisk=q.topRisk}C.applyResolvedReturnScore(x,pn,'progressive')}const rs=scored.slice().sort((a,b)=>a.r.rank-b.r.rank).slice(0,12).map(x=>x.ret).filter(Number.isFinite).sort((a,b)=>a-b),med=rs.length?rs[Math.floor(rs.length/2)]:null;if(Number.isFinite(med))for(const x of scored)if(Number.isFinite(x.ret))x.rawScore+=C.__clamp((med-x.ret)*6,-3,3)}
 C.applyPlayerQualitySafetyGate(scored,pn);C.normalizeCoachScores(scored);const cmp=(a,b)=>b.score-a.score||b.rawScore-a.rawScore||a.r.rank-b.r.rank;scored.sort(cmp);if(!scored.length)throw Error('empty PairSum board');
 if(!([12,32].includes(pn)&&next))return{chosen:scored[0].p,diag:{active:false,top:scored.slice(0,5).map(x=>x.p.name)}};
 const frontier=scored.slice(0,5),stateString=s.picks.map(p=>String(p.pick_no)+':'+String(p.player_id)).join('|')+'|'+pn+'|'+next+'|PAIRSUM_V2';let h=2166136261>>>0;for(let i=0;i<stateString.length;i++){h^=stateString.charCodeAt(i);h=Math.imul(h,16777619)>>>0}
 const countsFrom=(pk,slot)=>{const c={QB:0,RB:0,WR:0,TE:0,K:0,DEF:0};for(const p of pk){if(+p.draft_slot!==slot)continue;const pos=String(p.metadata?.position||'').toUpperCase();if(pos in c)c[pos]++}return c};
 const evalA=a=>{const ranks=[];for(let ri=0;ri<120;ri++){const rr=api.rng((h+Math.imul(ri+1,2654435761))>>>0),av=new Set(s.available),pk=s.picks.map(p=>({...p,metadata:{...(p.metadata||{})}})),md={...s.pm};ok(av.has(a.p.key),'inner candidate');av.delete(a.p.key);md[a.p.key]=api.pmeta(a.p);pk.push({pick_no:pn,draft_slot:9,player_id:a.p.key,metadata:{position:a.p.pos,player_name:a.p.name,team:a.p.team}});for(let k=pn+1;k<next;k++){const slot=api.slotAt(k);ok(slot!==9,'geometry');const name=api.ACTIVE[slot],c=countsFrom(pk,slot),sp=api.special(rr,name,c,k);if(sp){const id=`__joint_${sp}_${k}_${ri}`;md[id]={full_name:sp+' placeholder '+k,position:sp};pk.push({pick_no:k,draft_slot:slot,player_id:id,metadata:{position:sp,player_name:sp+' placeholder '+k}});continue}const board=[...av].map(key=>players[key]).filter(Boolean).sort((x,y)=>x.panel-y.panel||x.adp-y.adp).slice(0,70),weights=board.map(p=>api.oppWeight(p,k,c,name,'baseline')),ch=api.wpick(rr,board,weights);ok(ch&&av.has(ch.key),'inner opponent');av.delete(ch.key);md[ch.key]=api.pmeta(ch);pk.push({pick_no:k,draft_slot:slot,player_id:ch.key,metadata:{position:ch.pos,player_name:ch.name,team:ch.team}})}const uc=countsFrom(pk,9);let fp=[...av].map(key=>players[key]).filter(Boolean).filter(p=>!(p.pos==='QB'&&uc.QB>=1)&&!(p.pos==='TE'&&uc.TE>=1));const missing=['QB','RB','WR','TE'].filter(pos=>(uc[pos]||0)===0),remain=api.USER_PICKS.filter(x=>x>=next).length;if(missing.length&&remain<=missing.length){const f=fp.filter(p=>missing.includes(p.pos));if(f.length)fp=f}const nxt=fp.map(p=>({p,r:C.rankFor(p.name,p.pos)})).filter(x=>x.r).sort((x,y)=>x.r.rank-y.r.rank||x.p.adp-y.p.adp)[0];ok(nxt,'inner next');ranks.push(+nxt.r.rank)}return ranks.reduce((a,b)=>a+b,0)/ranks.length};
 const rows=frontier.map(x=>({x,currentPanel:+x.r.rank,meanNext:evalA(x)}));for(const r of rows)r.packageCost=r.currentPanel+r.meanNext;rows.sort((a,b)=>a.packageCost-b.packageCost||cmp(a.x,b.x));return{chosen:rows[0].x.p,diag:{active:true,rows:rows.map(r=>({name:r.x.p.name,currentPanel:r.currentPanel,meanNext:r.meanNext,packageCost:r.packageCost}))}}}
function userPick(api,players,s,pn,policy){const before=s.r.snapshot();let d;if(policy==='MARKET_NEUTRAL')d={chosen:marketChoice(api,players,s,pn),diag:null};else if(policy==='PAIRSUM_LONG2')d=pairSumChoice(api,players,s,pn);else throw Error('policy '+policy);ok(stable(before)===stable(s.r.snapshot()),'user decision advanced outer RNG '+pn+' '+policy);const ch=d.chosen;ok(ch&&s.available.has(ch.key),'user '+pn);s.available.delete(ch.key);s.rosters[9].push(ch);api.addPick(s.picks,s.pm,pn,9,ch);return{name:ch.name,pos:ch.pos,key:ch.key,diag:d.diag}}
function advance(api,players,s,target,policy='MARKET_NEUTRAL'){for(let pn=s.nextPn;pn<target;pn++){if(api.slotAt(pn)===9)userPick(api,players,s,pn,policy);else opponent(api,players,s,pn);s.nextPn=pn+1}return s}
function earlyLegal(api,s,p){const c=api.counts(s.rosters[9]);return !(p.pos==='QB'&&c.QB>=1)&&!(p.pos==='TE'&&c.TE>=1)}
function frontier(api,players,s,pn){const a=[...s.available].map(k=>players[k]).filter(Boolean).filter(p=>earlyLegal(api,s,p)),p=a.slice().sort((x,y)=>x.panel-y.panel||x.adp-y.adp).slice(0,8),m=a.slice().sort((x,y)=>x.adp-y.adp||x.panel-y.panel).slice(0,8),u=new Map([...p,...m].map(x=>[x.key,x]));if(pn===12){const b=a.find(x=>x.name==='Brock Bowers');if(b)u.set(b.key,b)}return[...u.values()].sort((x,y)=>x.panel-y.panel||x.adp-y.adp)}
function prefixData(s){return{picks:s.picks,available:[...s.available].sort(),rosters:Object.fromEntries(Object.entries(s.rosters).map(([k,v])=>[k,v.map(p=>p.key)])),rng:s.r.snapshot(),nextPn:s.nextPn}}
function force(api,s,p,pn){ok(s.nextPn===pn,'treatment pn');ok(s.available.has(p.key),'unavailable treatment');ok(earlyLegal(api,s,p),'illegal treatment');const r=s.r.snapshot();s.available.delete(p.key);s.rosters[9].push(p);api.addPick(s.picks,s.pm,pn,9,p);ok(stable(r)===stable(s.r.snapshot()),'treatment RNG');s.nextPn=pn+1}
function finish(api,players,s,policy){const decisions=[];for(let pn=s.nextPn;pn<=150;pn++){if(api.slotAt(pn)===9)decisions.push({pick:pn,...userPick(api,players,s,pn,policy)});else opponent(api,players,s,pn);s.nextPn=pn+1}const mine=s.rosters[9].filter(p=>['QB','RB','WR','TE'].includes(p.pos)),c=api.counts(mine);ok(mine.length===15,'roster length');ok(c.QB>=1&&c.RB>=1&&c.WR>=2&&c.TE>=1,'starter feasibility');return{decisions,mine,c}}
(async()=>{const fix=await getFixture(),api=apiFrom(fix);await api.loadMeta();const players=api.buildPlayers();ok(Object.keys(players).length>=225,'pool');api.initRepl(players);const seeds=[459272001],policies=['MARKET_NEUTRAL','PAIRSUM_LONG2'],states=[];for(const seed of seeds){for(const pn of[9,12]){const base=advance(api,players,init(api,players,seed),pn,'MARKET_NEUTRAL'),prefix=prefixData(base),pf=sha(prefix),f=frontier(api,players,base,pn);ok(f.length>=6,'frontier');const branches=[];for(const cand of f){for(const policy of policies){const s=clone(base);ok(sha(prefixData(s))===pf,'clone prefix');force(api,s,cand,pn);const fin=finish(api,players,s,policy);branches.push({candidate:{key:cand.key,name:cand.name,pos:cand.pos,panel:cand.panel,adp:cand.adp},continuation:policy,prefix_fingerprint:pf,treatment_rng:prefix.rng,user_roster:fin.mine.map(x=>({key:x.key,name:x.name,pos:x.pos,panel:x.panel,adp:x.adp})),position_counts:fin.c,continuation_decisions:fin.decisions,complete_picks:s.picks,free_agent_ids:[...s.available].sort(),final_rng:s.r.snapshot(),complete_fingerprint:sha({picks:s.picks,fa:[...s.available].sort(),rng:s.r.snapshot()})})}}states.push({seed,treatment_pick:pn,prefix_policy:pn===12?'MARKET_NEUTRAL at 1.09':'none',prefix_fingerprint:pf,prefix_picks:prefix.picks,frontier:f.map(x=>({key:x.key,name:x.name,pos:x.pos,panel:x.panel,adp:x.adp})),branches})}}
 const out={schema:1,status:'PASS',raw_only:true,outcome_evaluated:false,kernel:'actual validated rc4.59 full-policy opponent kernel',seed_family:'fresh 459272xxx',seeds,policies,frontier_rule:'outcome-blind union top-8 selected-panel + top-8 Sleeper ADP; Bowers explicitly retained at 2.02 if legal',prefix_for_2_02:'MARKET_NEUTRAL at 1.09 for first diagnostic state only; later screen must condition across plausible 1.09 branches',pairsum_definition:'exact screened PairSum-v2 LONG2: canonical Coach except package-cost lookahead at picks 12 and 32, frontier 5, 120 inner CRN rollouts, current selected-panel rank + expected best legal next selected-panel rank',metadata_fixture_players:Object.keys(fix).length,states};fs.mkdirSync('counterfactual_2026',{recursive:true});fs.writeFileSync('counterfactual_2026/RC459_DECISION_COUNTERFACTUAL_RAW_SCREEN_2026.json',JSON.stringify(out));console.log(JSON.stringify({status:'PASS',states:states.length,branches:states.reduce((n,s)=>n+s.branches.length,0),frontiers:states.map(s=>({pick:s.treatment_pick,n:s.frontier.length,names:s.frontier.map(x=>x.name)}))},null,2))})().catch(e=>{console.error(e.stack||e);process.exit(2)});
