'use strict';
const fs=require('fs');
const IN='counterfactual_2026/RC459_REALISTIC_TURN12_2026.json';
const OUT='counterfactual_2026/RC459_REALISTIC_TURN12_REALITY_DIAGNOSTIC_2026.json';
const x=JSON.parse(fs.readFileSync(IN,'utf8'));if(x.status!=='PASS'||!x.raw_only||x.outcome_evaluated!==false)throw Error('raw gate');
const pool=x.player_pool_snapshot, market=x.market_anchors;
const byPick9={}, valid=[], rejected=[];
for(const st of x.states){const b=st.branches[0],viol=[];for(const p of b.complete_picks){if(p.pick_no!==10&&p.pick_no!==11)continue;const md=pool[String(p.player_id)];if(md&&Number.isFinite(md.adp)&&md.adp-p.pick_no>15)viol.push({pick:p.pick_no,name:p.metadata?.player_name,adp:md.adp,reach_picks:+(md.adp-p.pick_no).toFixed(1)});}if(viol.length){rejected.push({seed:st.seed,forced_1_09:st.forced_1_09.name,violations:viol});continue}valid.push(st);
 const k=st.forced_1_09.name,a=byPick9[k]||(byPick9[k]={n:0,best_at_12:{},core_survivors:{},dutch_pairs:{}});a.n++;const pp={};for(const p of b.complete_picks)if(p.pick_no===10||p.pick_no===11)pp[p.pick_no]=p.metadata?.player_name;const pair=(pp[10]||'?')+' / '+(pp[11]||'?');a.dutch_pairs[pair]=(a.dutch_pairs[pair]||0)+1;const f=st.primary_frontier.filter(p=>Number.isFinite(p.market_anchor)).slice().sort((u,v)=>u.market_anchor-v.market_anchor);if(f.length){a.best_at_12[f[0].name]=(a.best_at_12[f[0].name]||0)+1;}for(const p of f)if(p.market_anchor<=12)a.core_survivors[p.name]=(a.core_survivors[p.name]||0)+1;}
for(const a of Object.values(byPick9)){for(const key of ['best_at_12','core_survivors','dutch_pairs'])a[key]=Object.fromEntries(Object.entries(a[key]).sort((u,v)=>v[1]-u[1]||u[0].localeCompare(v[0])));}
const everyHasTop12=valid.every(st=>st.primary_frontier.some(p=>Number.isFinite(p.market_anchor)&&p.market_anchor<=12));
const out={status:'PASS',source_raw:IN,source_states:x.states.length,valid_strategy_states:valid.length,rejected_states:rejected.length,opponent_early_major_reach_rule:'reject state if Dutch pick 10/11 Sleeper ADP is >15 picks later than pick number; generous reality guard, diagnostic only',rejected,every_valid_state_has_market_anchor_12_or_better_at_2_02:everyHasTop12,interpretation:'At the 9/10 turn only two Dutch picks intervene. Under valid simulated boards, a top-turn player always survives to 2.02; TAKE/WAIT should therefore compare pair construction and Dutch survival, not assume pick12 starts below rank 12.',by_pick_1_09:byPick9};fs.writeFileSync(OUT,JSON.stringify(out,null,2));console.log(JSON.stringify({status:'PASS',source_states:x.states.length,valid:valid.length,rejected:rejected.length,every_valid_state_has_top12_faller:everyHasTop12,by_pick_1_09:Object.fromEntries(Object.entries(byPick9).map(([k,v])=>[k,{n:v.n,best_at_12:v.best_at_12}]))},null,2));
