'use strict';
const fs=require('fs'),vm=require('vm'),crypto=require('crypto');
const app=fs.readFileSync('app.js','utf8'),fx=JSON.parse(fs.readFileSync('diagnostics_2026/RC459_DYNAMIC_FIXTURES_2026.json','utf8')),panel=JSON.parse(fs.readFileSync('freeze_2026/FRESH_2026_PANEL_PAYLOAD.json','utf8')),raw=JSON.parse(fs.readFileSync('freeze_2026/FRESH_2026_MARKET_PANEL_RAW.json','utf8')),parity=JSON.parse(fs.readFileSync('diagnostics_2026/RC459_TRANSITIVE_POLICY_SOURCE_PARITY_2026_GATE.json','utf8'));
const APP_SHA='1de9c6dcbd39bec35dffd2b43575260da6601abf3a9a29fe329ffeb8a4065fa3',TIER_SHA='5e74a74a78cc0b9ffa587d60ba568dd3a03628082b88a491b916cdcbf6378d84';
if(parity.status!=='PASS'||parity.numbered_rc459_app_sha256!==APP_SHA||parity.source_item_count!==58||parity.matching_count!==58)throw Error('58/58 numbered rc4.59 source lock not PASS');
function fn(name){const st=app.indexOf('function '+name+'(');if(st<0)throw Error('missing '+name);let d=0,q=false;for(let i=st;i<app.length;i++){if(app[i]==='{'){d++;q=true}else if(app[i]==='}'&&q&&--d===0)return app.slice(st,i+1)}throw Error('unclosed '+name)}
function lineConst(name){const st=app.indexOf('const '+name+'='),en=app.indexOf('\n',st);if(st<0)throw Error('missing const '+name);return app.slice(st,en).trim()}
function between(a,b){const st=app.indexOf(a),en=app.indexOf(b,st);if(st<0||en<0)throw Error('range '+a);return app.slice(st,en)}
const exactAssignTiers="function assignTiers(map){for(const pos of ['QB','RB','WR','TE']){const rows=Object.values(map).filter(x=>x.pos===pos).sort((a,b)=>a.rank-b.rank);let tier=1,prev=null;for(const row of rows){if(prev!=null&&row.rank-prev>=4)tier++;row.tier=tier;prev=row.rank}}}";
if(crypto.createHash('sha256').update(exactAssignTiers).digest('hex')!==TIER_SHA)throw Error('embedded numbered assignTiers hash');
const names=['pinfo','draftSlotAtPick','panelHasVerifiedExperts','panelFor','rankFor','adpFor','agreement','returnChance','rosterState','rosterExceptionPenalty','lateUpsideBonus','progressiveStage','progressiveUpsideBonus','injuryStashAdjustment','marginalRosterUtility','managerProfile','managerProfilesActive','managerPhase','liveManagerStateForProfile','managerHistoryPosMult','specialPositionHazard','chooseSpecialTeamPick','rosterBySlot','slotsBetween','endgameSkillShare','basePositionPlausible','expectedSkillShare','plausibleFor','candidateManagerMod','stressProfile','simNeedWeight','seededRng','weightedChoice','simCandidateWeight','cloneRosters','returnV2Confidence','simulateReturnV2','draftPhaseNeedFactor','normalizeCoachScores','playerQualitySafetyThreshold','applyPlayerQualitySafetyGate','tierContext','positionalAlternativeContext','valueLabel','bestAvailablePanelRank','playerQualityBaseScore','scoreCandidate','applyResolvedReturnScore'];
const source=[lineConst('norm'),lineConst('clamp'),between('const MANAGER_PROFILES=','\nconst MANAGER_PROFILE_DATA='),between('const MANAGER_PROFILE_DATA=','\nconst MANAGER_PROFILE_SOURCE_HASH='),'let LIVE_MANAGER_ADAPTATION_STATE={};',exactAssignTiers,...names.map(fn),'this.__norm=norm;this.__clamp=clamp;'].join('\n');
function context(shadow=0){const panelRanks=structuredClone(panel.panels),panels={},rankCache={};for(const[id,members]of Object.entries(panel.effective_members)){panels[id]={name:id,members:Object.fromEntries(members.map(x=>[x,1]))};for(const x of members)rankCache[x]={verifiedIndividual:true,duplicateOf:null}}const c={console,Math,Date,JSON,Object,Array,Number,String,Set,Map,Infinity,structuredClone,panels,panelRanks,rankCache,positionPanels:{QB:'qb',RB:'rb',WR:'wr',TE:'te'},activePanelId:'standard',adp:Object.fromEntries(raw.pool_rows.map(x=>[x.key,x.adp])),els:{season:{value:'2026'}},researchResidualShadow:()=>({model:'shadow-neutral',delta:shadow,active:shadow!==0,components:[]})};vm.createContext(c);vm.runInContext(source,c);for(const x of Object.values(c.panelRanks))c.assignTiers(x);return c}
function run(f,shadow=0){const c=context(shadow),mine=f.picks.filter(p=>+p.draft_slot===9),state=c.rosterState(mine,f.players,f.current),ranked=f.available.map(p=>({p,r:c.rankFor(p.name,p.pos)})).filter(x=>x.r).sort((a,b)=>a.r.rank-b.r.rank).map(x=>x.p);if(ranked.length<24)throw Error('pool '+f.id);for(const pos of['QB','RB','WR','TE'])if(state.counts[pos]!==+(f.expected_rosters['9'][pos]||0))throw Error('user map '+f.id+' '+pos);const rr=c.rosterBySlot(f.picks,f.players,10);for(let s=1;s<=10;s++)for(const pos of['QB','RB','WR','TE','K','DEF'])if(+(rr[s][pos]||0)!==+(f.expected_rosters[String(s)][pos]||0))throw Error('roster map '+f.id+' '+s+' '+pos);let scored=ranked.map(p=>({p,...c.scoreCandidate(p,f.current,f.next,state,ranked,'progressive')}));const rv=c.simulateReturnV2({current:f.current,next:f.next,picks:f.picks,players:f.players,teams:10,map:f.managerMap,rankedAvailable:ranked,mode:'mock',userSlot:9},'baseline',900);for(const x of scored){const q=rv.players[c.__norm(x.p.name)];if(q){x.ret=q.ret;x.returnConfidence=q.confidence;x.topRisk=q.topRisk}c.applyResolvedReturnScore(x,f.current,'progressive')}const rs=scored.slice().sort((a,b)=>a.r.rank-b.r.rank).slice(0,12).map(x=>x.ret).filter(Number.isFinite).sort((a,b)=>a-b),med=rs.length?rs[Math.floor(rs.length/2)]:null;if(Number.isFinite(med))for(const x of scored)if(Number.isFinite(x.ret))x.rawScore+=c.__clamp((med-x.ret)*6,-3,3);const safety=c.applyPlayerQualitySafetyGate(scored,f.current);c.normalizeCoachScores(scored);scored.sort((a,b)=>b.score-a.score||b.rawScore-a.rawScore||a.r.rank-b.r.rank);return{id:f.id,current:f.current,next:f.next,state,ranked_pool:ranked.length,return_runs:rv.runs,map_coverage:rv.mapCoverage,quality_safety:safety,top:scored.slice(0,10).map((x,i)=>({rank:i+1,name:x.p.name,pos:x.p.pos,panel_rank:x.r.rank,adp:Number.isFinite(x.a)?x.a:null,return_prob:Number.isFinite(x.ret)?+x.ret.toFixed(4):null,return_confidence:x.returnConfidence??null,raw_score:+x.rawScore.toFixed(4),score:x.score}))}}
const rows=fx.fixtures.map(f=>run(f,0));const reps=[];for(const turn of [9,29,49,69]){const f=fx.fixtures.find(x=>x.current===turn);if(f)reps.push(f)}let deterministic=true,shadowInvariant=true;for(const f of reps){const a=rows.find(x=>x.id===f.id),b=run(f,0),z=run(f,99);if(JSON.stringify(a)!==JSON.stringify(b))deterministic=false;if(a.top.map(x=>x.name).join('|')!==z.top.map(x=>x.name).join('|'))shadowInvariant=false}const top1={};for(const r of rows){top1[r.current]??={};top1[r.current][r.top[0].name]=(top1[r.current][r.top[0].name]||0)+1}const ok=rows.length===fx.fixture_count&&rows.every(r=>r.return_runs===900&&r.ranked_pool>=24)&&deterministic&&shadowInvariant,out={schema:4,status:ok?'PASS':'FAIL_CLOSED',numbered_rc459_app_sha256:APP_SHA,source_lock:'transitive 58/58 + embedded assignTiers exact numbered hash',freeze_package_sha256:fx.freeze_package_sha256,fixture_count:rows.length,turns:fx.turns,repeat_shadow_validation_fixtures:reps.map(x=>x.id),deterministic_repeatability:deterministic,shadow_live_order_invariant:shadowInvariant,all_return_runs_900:rows.every(r=>r.return_runs===900),all_input_rosters_exact:true,top1_by_turn:top1,policy_ranking_certified:false,fixtures:rows};fs.writeFileSync('diagnostics_2026/RC459_DYNAMIC_COACH_EXECUTION_2026.json',JSON.stringify(out,null,2));const keys=['status','numbered_rc459_app_sha256','source_lock','freeze_package_sha256','fixture_count','turns','repeat_shadow_validation_fixtures','deterministic_repeatability','shadow_live_order_invariant','all_return_runs_900','all_input_rosters_exact','top1_by_turn','policy_ranking_certified'];fs.writeFileSync('diagnostics_2026/RC459_DYNAMIC_COACH_EXECUTION_2026_GATE.json',JSON.stringify(Object.fromEntries(keys.map(k=>[k,out[k]])),null,2));console.log(JSON.stringify({status:out.status,fixture_count:out.fixture_count,reps:reps.length,deterministic,shadowInvariant,top1},null,2));if(!ok)process.exit(2);
