'use strict';
/* Research-only production-like comparator for the fresh 120-seed family.
   Keeps the metadata-safe mapping used by the current research baseline, but deliberately
   leaves PlayerQualitySafetyGate on the FULL candidate board exactly as the production Coach
   does. This isolates the repeat-QB/TE safety-resurrection guard as the treatment.

   IMPORTANT: this comparator must OBSERVE, not suppress, pathological autonomous full-safety
   rosters. Therefore no QB/RB/WR/TE completion quota is asserted. A completed 15-pick roster
   is persisted with its actual position counts and an explicit feasibility diagnostic. The
   independent paired evaluator already supplies replacement-level starters for missing
   positions, so invalid composition remains measurable evidence rather than a harness crash. */
const fs=require('fs'),crypto=require('crypto'),cp=require('child_process'),path=require('path');
const POLICY='research/rc459_full_policy_paired_2026.js',FULL='research/rc459_realistic_fullmock_tier_audit_2026.js';
const POLICY_BLOB='5c313bb54538139145761c3885d29f480e138b45',FULL_BLOB='c1f26da2877f9b01e25ea4926c03c398e7878876';
function gitBlob(s){const b=Buffer.from(s);return crypto.createHash('sha1').update(Buffer.from(`blob ${b.length}\0`)).update(b).digest('hex')}
const policy0=fs.readFileSync(POLICY,'utf8'),full0=fs.readFileSync(FULL,'utf8');if(gitBlob(policy0)!==POLICY_BLOB)throw Error('POLICY_DRIFT '+gitBlob(policy0));if(gitBlob(full0)!==FULL_BLOB)throw Error('FULL_DRIFT '+gitBlob(full0));
const metaRe=/let meta=\{\};\s*async function loadMeta\(\)\{[\s\S]*?\}\s*function buildPlayers\(\)\{[\s\S]*?\}\s*function pmeta/;if((policy0.match(new RegExp(metaRe.source,'g'))||[]).length!==1)throw Error('META_ANCHOR_DRIFT');
const safeMeta=`let meta={};
async function loadMeta(){const res=await fetch('https://api.sleeper.app/v1/players/nfl',{headers:{'User-Agent':'PITTI-FullSafetyBaseline/1.0'}});if(!res.ok)throw Error('metadata fetch '+res.status);const j=await res.json();meta={};for(const [sid,p] of Object.entries(j||{})){const name=p.full_name||[p.first_name,p.last_name].filter(Boolean).join(' ');if(!name)continue;const nk=nrm(name),position=String(p.position||p.fantasy_positions?.[0]||'').toUpperCase(),rec={sleeperId:String(sid),team:String(p.team||'FA'),yearsExp:p.years_exp==null?null:+p.years_exp,injury:p.injury_status||null,bye:p.bye_week??null,searchRank:p.search_rank??null,position};if(position)(meta[nk+'|'+position]??=[]).push(rec)}}
function buildPlayers(){const out={};for(const x of raw.pool_rows){if(!['QB','RB','WR','TE'].includes(x.pos))continue;if(['jaydenhiggins','rickypearsall'].includes(nrm(x.name)))continue;const r=C.rankFor(x.name,x.pos);if(!r)continue;const matches=meta[nrm(x.name)+'|'+String(x.pos).toUpperCase()]||[];if(matches.length>1)throw Error('AMBIGUOUS_POSITION_METADATA '+x.name+' '+x.pos);const md=matches[0]||{};if(nrm(x.name)==='justinjefferson'&&String(x.pos).toUpperCase()==='WR'&&(md.position!=='WR'||md.team!=='MIN'||md.sleeperId!=='6794'))throw Error('JUSTIN_JEFFERSON_WR_METADATA_NOT_RESOLVED');out[String(x.key)]={key:String(x.key),id:String(x.key),name:x.name,pos:x.pos,team:md.team||'FA',yearsExp:md.yearsExp,injury:md.injury,bye:md.bye,searchRank:md.searchRank,panel:+r.rank,adp:Number.isFinite(x.adp)?+x.adp:+r.rank}}return out}
function pmeta`;
let policy=policy0.replace(metaRe,safeMeta);if(policy===policy0)throw Error('META_PATCH_NOOP');let full=full0;
const feasibilityAnchor="H.ok(c.QB>=1&&c.RB>=1&&c.WR>=2&&c.TE>=1,'starter feasibility');";if(full.split(feasibilityAnchor).length!==2)throw Error('FEASIBILITY_ANCHOR_DRIFT');full=full.replace(feasibilityAnchor,"H.ok(mine.length===15,'user roster length');");
const returnAnchor="return{seed,decisions,user_roster:mine.map(p=>({name:p.name,pos:p.pos,panel:p.panel,adp:p.adp})),position_counts:c,free_agent_ids:[...s.available].sort(),complete_fingerprint:H.sha({picks:s.picks,fa:[...s.available].sort(),rng:s.r.snapshot()})}";if(full.split(returnAnchor).length!==2)throw Error('RETURN_ANCHOR_DRIFT');full=full.replace(returnAnchor,"return{seed,decisions,user_roster:mine.map(p=>({name:p.name,pos:p.pos,panel:p.panel,adp:p.adp})),position_counts:c,starter_feasibility:{QB1:c.QB>=1,RB1:c.RB>=1,WR2:c.WR>=2,TE1:c.TE>=1,user_policy_minimum:c.QB>=1&&c.RB>=1&&c.WR>=2},free_agent_ids:[...s.available].sort(),complete_fingerprint:H.sha({picks:s.picks,fa:[...s.available].sort(),rng:s.r.snapshot()})}" );
const shard=Number(process.env.PITTI_SHARD);if(!Number.isInteger(shard)||shard<0||shard>11)throw Error('PITTI_SHARD 0..11 required');const seedAnchor="const seeds=Array.from({length:60},(_,i)=>459710001+i),drafts=[];";if(full.split(seedAnchor).length!==2)throw Error('SEED_ANCHOR_DRIFT');const start=459820001+10*shard;full=full.replace(seedAnchor,`const seeds=Array.from({length:10},(_,i)=>${start}+i),drafts=[];`);
fs.writeFileSync(POLICY,policy);const tmp=path.join('/tmp',`pitti_rc463_full_safety_baseline_${shard}.js`);fs.writeFileSync(tmp,full);let status=2;try{const r=cp.spawnSync(process.execPath,[tmp],{stdio:'inherit',env:process.env});if(r.error)throw r.error;status=r.status??2;if(status===0){const src='simulation_2026/RC459_REALISTIC_FULLMOCK_TIER_AUDIT_2026.json';if(!fs.existsSync(src))throw Error('OUTPUT_MISSING');const x=JSON.parse(fs.readFileSync(src,'utf8'));if(x.status!=='PASS'||x.seeds!==10||x.drafts?.length!==10)throw Error('OUTPUT_INVALID');const expected=Array.from({length:10},(_,i)=>start+i);if(JSON.stringify(x.drafts.map(d=>d.seed))!==JSON.stringify(expected))throw Error('SEED_MISMATCH');x.metadata_mapping='normalized-name + position, unique-match fail-closed';x.rc463_full_safety_baseline_roster_export=true;x.rc463_seed_family='459820001..459820120';x.safety_policy='full production-like PlayerQualitySafetyGate candidate board; no repeat-QB/TE resurrection guard';x.composition_policy='observe completed 15-pick autonomous Coach roster exactly; do not force/require positional starter feasibility';x.production_mutation=false;const dst=`simulation_2026/RC463_FULL_SAFETY_BASELINE_ROSTER_SHARD_${shard}_2026.json`;fs.renameSync(src,dst);fs.writeFileSync(dst,JSON.stringify(x));console.log(JSON.stringify({status:'PASS',shard,start,end:start+9,invalid_user_policy:x.drafts.filter(d=>!d.starter_feasibility?.user_policy_minimum).length,output:dst},null,2))}}finally{fs.writeFileSync(POLICY,policy0)}if(status!==0)process.exit(status);
