'use strict';
/* Research-only extreme-gap screen. Fixed threshold -50; no production mutation.
   Exact same mechanism as the parity-validated threshold harness: only repeated-position QB/TE
   Safety resurrection is reverted when original raw gap to best legal RB/WR is below -50.
   Natural pre-Safety leaders and existing elite Exceptional-Slide semantics remain admissible. */
const fs=require('fs'),cp=require('child_process'),path=require('path'),crypto=require('crypto');
const BASE='research/rc463_full_safety_baseline_roster_120_shard_2026.js';
const BASE_BLOB='aac28c9b443b81705355728087acdc60912b86eb';
const THR=-50;
function gitBlob(s){const b=Buffer.from(s);return crypto.createHash('sha1').update(Buffer.from(`blob ${b.length}\0`)).update(b).digest('hex')}
const base0=fs.readFileSync(BASE,'utf8');if(gitBlob(base0)!==BASE_BLOB)throw Error('BASE_DRIFT '+gitBlob(base0));
const shard=Number(process.env.PITTI_SHARD);if(!Number.isInteger(shard)||shard<0||shard>11)throw Error('PITTI_SHARD 0..11 required');
if(!process.env.PITTI_META_SNAPSHOT||!fs.existsSync(process.env.PITTI_META_SNAPSHOT))throw Error('PITTI_META_SNAPSHOT missing');
const shared="const j=JSON.parse(require('fs').readFileSync(process.env.PITTI_META_SNAPSHOT,'utf8'));";
const metaRe=/const res=await fetch\('https:\/\/api\.sleeper\.app\/v1\/players\/nfl',\{headers:\{'User-Agent':'PITTI-FullSafetyBaseline\/1\.0'\}\}\);if\(!res\.ok\)throw Error\('metadata fetch '\+res\.status\);const j=await res\.json\(\);/g;
if((base0.match(metaRe)||[]).length!==1)throw Error('METADATA_ANCHOR_DRIFT');let src=base0.replace(metaRe,shared);
const shardAnchor="const shard=Number(process.env.PITTI_SHARD);";if(src.split(shardAnchor).length!==2)throw Error('SHARD_ANCHOR_DRIFT');
const treatment=`\nconst __safetyAnchor='const safety=C.applyPlayerQualitySafetyGate(scored,pn);';\nif(full.split(__safetyAnchor).length!==2)throw Error('SAFETY_ANCHOR_DRIFT');\nfull=full.replace(__safetyAnchor,\`const __preSafetyRaw=new Map(scored.map(x=>[String(x.p.key),Number(x.rawScore)]));const __preValid=scored.filter(x=>x?.r&&Number.isFinite(x.r.rank)&&Number.isFinite(x.rawScore)&&!x.hardExcluded&&!x.recommendationBlocked);const __preNatural=__preValid.slice().sort((a,b)=>b.rawScore-a.rawScore||a.r.rank-b.r.rank)[0]||null;const __preBestSkill=__preValid.filter(x=>x.p.pos==='RB'||x.p.pos==='WR').sort((a,b)=>b.rawScore-a.rawScore||a.r.rank-b.r.rank)[0]||null;const safety=C.applyPlayerQualitySafetyGate(scored,pn);const __promoted=scored.find(x=>x.valueSafety?.promoted===true)||null;if(__promoted&&(__promoted.p.pos==='QB'||__promoted.p.pos==='TE')&&Number(state.counts?.[__promoted.p.pos]||0)>=1){const __orig=__preSafetyRaw.get(String(__promoted.p.key));const __gap=(Number.isFinite(__orig)&&__preBestSkill)?__orig-Number(__preBestSkill.rawScore):null;const __elite=__promoted.p.pos==='QB'?(__promoted.r.rank<=45&&Number.isFinite(__promoted.a)&&pn-__promoted.a>=35):(__promoted.r.rank<=35&&Number.isFinite(__promoted.a)&&pn-__promoted.a>=30);const __natural=!!(__preNatural&&String(__preNatural.p.key)===String(__promoted.p.key));if(!__natural&&!__elite&&Number.isFinite(__gap)&&__gap<${THR}){__promoted.rawScore=__orig;__promoted.valueSafety={...__promoted.valueSafety,thresholdTreatmentSuppressed:true,preSafetyGapToBestSkill:__gap,treatmentThreshold:${THR}};__promoted.reasons=(__promoted.reasons||[]).filter(r=>!String(r).startsWith('Value-Safety Gate:'));}}\`);\n`;
src=src.replace(shardAnchor,treatment+shardAnchor);
const tmp=path.join('/tmp',`pitti_rc463_extreme_m50_${shard}.js`);fs.writeFileSync(tmp,src);const r=cp.spawnSync(process.execPath,[tmp],{stdio:'inherit',env:{...process.env,PITTI_SHARD:String(shard)}});if(r.error)throw r.error;if((r.status??2)!==0)process.exit(r.status??2);
const baselineOut=`simulation_2026/RC463_FULL_SAFETY_BASELINE_ROSTER_SHARD_${shard}_2026.json`;if(!fs.existsSync(baselineOut))throw Error('OUTPUT_MISSING');const x=JSON.parse(fs.readFileSync(baselineOut,'utf8'));if(x.status!=='PASS'||x.drafts?.length!==10)throw Error('OUTPUT_INVALID');x.rc463_presafety_threshold_treatment=true;x.threshold=THR;x.metadata_snapshot_sha256=crypto.createHash('sha256').update(fs.readFileSync(process.env.PITTI_META_SNAPSHOT)).digest('hex');x.safety_policy='Full Safety except ordinary repeated-position QB/TE Safety resurrection with original gap < -50; natural leader and existing elite slide preserved';x.production_mutation=false;const dst=`simulation_2026/RC463_PRESAFETY_EXTREME_M50_SHARD_${shard}_2026.json`;fs.writeFileSync(dst,JSON.stringify(x));fs.unlinkSync(baselineOut);console.log(JSON.stringify({status:'PASS',threshold:THR,shard,output:dst,metadata_sha256:x.metadata_snapshot_sha256},null,2));