'use strict';
/* Research-only instrumentation of the exact rc4.63 production-like full-safety comparator.
   Captures ORIGINAL rawScore state immediately before PlayerQualitySafetyGate mutates a safety
   leader to maxRaw+0.25. The instrumentation must not alter ranking, RNG, availability, policy,
   or roster choices. Same 459820001..459820120 paired seed family. */
const fs=require('fs'),crypto=require('crypto'),cp=require('child_process'),path=require('path');
const BASE='research/rc463_full_safety_baseline_roster_120_shard_2026.js';
const EXPECT='aac28c9b443b81705355728087acdc60912b86eb';
function gitBlob(s){const b=Buffer.from(s);return crypto.createHash('sha1').update(Buffer.from(`blob ${b.length}\0`)).update(b).digest('hex')}
const base0=fs.readFileSync(BASE,'utf8');if(gitBlob(base0)!==EXPECT)throw Error('BASE_DRIFT '+gitBlob(base0));
/* Execute the baseline generator indirectly, but first reproduce its source transformation so
   the generated FULL source can be instrumented before execution. */
const POLICY='research/rc459_full_policy_paired_2026.js',FULL='research/rc459_realistic_fullmock_tier_audit_2026.js';
const POLICY_BLOB='5c313bb54538139145761c3885d29f480e138b45',FULL_BLOB='c1f26da2877f9b01e25ea4926c03c398e7878876';
const policy0=fs.readFileSync(POLICY,'utf8'),full0=fs.readFileSync(FULL,'utf8');if(gitBlob(policy0)!==POLICY_BLOB)throw Error('POLICY_DRIFT '+gitBlob(policy0));if(gitBlob(full0)!==FULL_BLOB)throw Error('FULL_DRIFT '+gitBlob(full0));
const metaRe=/let meta=\{\};\s*async function loadMeta\(\)\{[\s\S]*?\}\s*function buildPlayers\(\)\{[\s\S]*?\}\s*function pmeta/;if((policy0.match(new RegExp(metaRe.source,'g'))||[]).length!==1)throw Error('META_ANCHOR_DRIFT');
const safeMeta=`let meta={};
async function loadMeta(){const res=await fetch('https://api.sleeper.app/v1/players/nfl',{headers:{'User-Agent':'PITTI-FullSafetyPreSafety/1.0'}});if(!res.ok)throw Error('metadata fetch '+res.status);const j=await res.json();meta={};for(const [sid,p] of Object.entries(j||{})){const name=p.full_name||[p.first_name,p.last_name].filter(Boolean).join(' ');if(!name)continue;const nk=nrm(name),position=String(p.position||p.fantasy_positions?.[0]||'').toUpperCase(),rec={sleeperId:String(sid),team:String(p.team||'FA'),yearsExp:p.years_exp==null?null:+p.years_exp,injury:p.injury_status||null,bye:p.bye_week??null,searchRank:p.search_rank??null,position};if(position)(meta[nk+'|'+position]??=[]).push(rec)}}
function buildPlayers(){const out={};for(const x of raw.pool_rows){if(!['QB','RB','WR','TE'].includes(x.pos))continue;if(['jaydenhiggins','rickypearsall'].includes(nrm(x.name)))continue;const r=C.rankFor(x.name,x.pos);if(!r)continue;const matches=meta[nrm(x.name)+'|'+String(x.pos).toUpperCase()]||[];if(matches.length>1)throw Error('AMBIGUOUS_POSITION_METADATA '+x.name+' '+x.pos);const md=matches[0]||{};if(nrm(x.name)==='justinjefferson'&&String(x.pos).toUpperCase()==='WR'&&(md.position!=='WR'||md.team!=='MIN'||md.sleeperId!=='6794'))throw Error('JUSTIN_JEFFERSON_WR_METADATA_NOT_RESOLVED');out[String(x.key)]={key:String(x.key),id:String(x.key),name:x.name,pos:x.pos,team:md.team||'FA',yearsExp:md.yearsExp,injury:md.injury,bye:md.bye,searchRank:md.searchRank,panel:+r.rank,adp:Number.isFinite(x.adp)?+x.adp:+r.rank}}return out}
function pmeta`;
let policy=policy0.replace(metaRe,safeMeta);if(policy===policy0)throw Error('META_PATCH_NOOP');let full=full0;
const feasibilityAnchor="H.ok(c.QB>=1&&c.RB>=1&&c.WR>=2&&c.TE>=1,'starter feasibility');";if(full.split(feasibilityAnchor).length!==2)throw Error('FEASIBILITY_ANCHOR_DRIFT');full=full.replace(feasibilityAnchor,"H.ok(mine.length===15,'user roster length');");
const returnAnchor="return{seed,decisions,user_roster:mine.map(p=>({name:p.name,pos:p.pos,panel:p.panel,adp:p.adp})),position_counts:c,free_agent_ids:[...s.available].sort(),complete_fingerprint:H.sha({picks:s.picks,fa:[...s.available].sort(),rng:s.r.snapshot()})}";if(full.split(returnAnchor).length!==2)throw Error('RETURN_ANCHOR_DRIFT');full=full.replace(returnAnchor,"return{seed,decisions,user_roster:mine.map(p=>({name:p.name,pos:p.pos,panel:p.panel,adp:p.adp})),position_counts:c,starter_feasibility:{QB1:c.QB>=1,RB1:c.RB>=1,WR2:c.WR>=2,TE1:c.TE>=1,user_policy_minimum:c.QB>=1&&c.RB>=1&&c.WR>=2},free_agent_ids:[...s.available].sort(),complete_fingerprint:H.sha({picks:s.picks,fa:[...s.available].sort(),rng:s.r.snapshot()})}" );
/* Capture exactly the pre-mutation scored board. */
const safetyAnchor='const safety=C.applyPlayerQualitySafetyGate(scored,pn);';
if(full.split(safetyAnchor).length!==2)throw Error('SAFETY_ANCHOR_DRIFT');
full=full.replace(safetyAnchor,`const __preSafety=scored.map(x=>({key:String(x.p.key),name:x.p.name,pos:x.p.pos,panel:Number(x.r.rank),adp:Number.isFinite(x.a)?Number(x.a):null,raw:Number(x.rawScore),hardExcluded:!!x.hardExcluded,recommendationBlocked:!!x.recommendationBlocked}));const safety=C.applyPlayerQualitySafetyGate(scored,pn);`);
const coachReturn="return{chosen:scored[0].p,chosenRow:scored[0],top,safety,medianReturn:med,state,ranked}";
if(full.split(coachReturn).length!==2)throw Error('COACH_RETURN_ANCHOR_DRIFT');full=full.replace(coachReturn,"return{chosen:scored[0].p,chosenRow:scored[0],top,safety,medianReturn:med,state,ranked,preSafety:__preSafety}");
const userReturn="return{pick:pn,name:p.name,pos:p.pos,panel:+d.chosenRow.r.rank,adp:Number.isFinite(d.chosenRow.a)?+d.chosenRow.a:null,ret:Number.isFinite(d.chosenRow.ret)?+d.chosenRow.ret:null,score:d.chosenRow.score,raw:+d.chosenRow.rawScore.toFixed(3),safety:d.safety,median_return:d.medianReturn,flags,superior_available:superiorAvail,core_available:coreAvail,firstturn_available:firstAvail,top:d.top}";
if(full.split(userReturn).length!==2)throw Error('USER_RETURN_ANCHOR_DRIFT');
full=full.replace(userReturn,`const __chosenPre=d.preSafety.find(x=>x.key===String(p.key))||null;const __validPre=d.preSafety.filter(x=>!x.hardExcluded&&!x.recommendationBlocked&&Number.isFinite(x.raw));const __naturalPre=__validPre.slice().sort((a,b)=>b.raw-a.raw||a.panel-b.panel)[0]||null;const __bestSkillPre=__validPre.filter(x=>x.pos==='RB'||x.pos==='WR').sort((a,b)=>b.raw-a.raw||a.panel-b.panel)[0]||null;const __preSafetyAudit={chosen:__chosenPre,natural:__naturalPre,best_skill:__bestSkillPre,chosen_minus_natural:(__chosenPre&&__naturalPre)?__chosenPre.raw-__naturalPre.raw:null,chosen_minus_best_skill:(__chosenPre&&__bestSkillPre)?__chosenPre.raw-__bestSkillPre.raw:null,chosen_was_natural:!!(__chosenPre&&__naturalPre&&__chosenPre.key===__naturalPre.key),safety_triggered:!!d.safety?.triggered,roster_counts:{QB:Number(d.state?.counts?.QB||0),RB:Number(d.state?.counts?.RB||0),WR:Number(d.state?.counts?.WR||0),TE:Number(d.state?.counts?.TE||0)}};return{pick:pn,name:p.name,pos:p.pos,panel:+d.chosenRow.r.rank,adp:Number.isFinite(d.chosenRow.a)?+d.chosenRow.a:null,ret:Number.isFinite(d.chosenRow.ret)?+d.chosenRow.ret:null,score:d.chosenRow.score,raw:+d.chosenRow.rawScore.toFixed(3),safety:d.safety,pre_safety_audit:__preSafetyAudit,median_return:d.medianReturn,flags,superior_available:superiorAvail,core_available:coreAvail,firstturn_available:firstAvail,top:d.top}`);
const shard=Number(process.env.PITTI_SHARD);if(!Number.isInteger(shard)||shard<0||shard>11)throw Error('PITTI_SHARD 0..11 required');const seedAnchor="const seeds=Array.from({length:60},(_,i)=>459710001+i),drafts=[];";if(full.split(seedAnchor).length!==2)throw Error('SEED_ANCHOR_DRIFT');const start=459820001+10*shard;full=full.replace(seedAnchor,`const seeds=Array.from({length:10},(_,i)=>${start}+i),drafts=[];`);
fs.writeFileSync(POLICY,policy);const tmp=path.join('/tmp',`pitti_rc463_full_safety_presafety_${shard}.js`);fs.writeFileSync(tmp,full);let status=2;
try{const r=cp.spawnSync(process.execPath,[tmp],{stdio:'inherit',env:process.env});if(r.error)throw r.error;status=r.status??2;if(status===0){const src='simulation_2026/RC459_REALISTIC_FULLMOCK_TIER_AUDIT_2026.json';if(!fs.existsSync(src))throw Error('OUTPUT_MISSING');const x=JSON.parse(fs.readFileSync(src,'utf8'));if(x.status!=='PASS'||x.seeds!==10||x.drafts?.length!==10)throw Error('OUTPUT_INVALID');const expected=Array.from({length:10},(_,i)=>start+i);if(JSON.stringify(x.drafts.map(d=>d.seed))!==JSON.stringify(expected))throw Error('SEED_MISMATCH');for(const d of x.drafts)for(const z of d.decisions)if(!z.pre_safety_audit?.chosen)throw Error('PRESAFETY_MISSING '+d.seed+' '+z.pick);x.metadata_mapping='normalized-name + position, unique-match fail-closed';x.rc463_full_safety_presafety_instrumented=true;x.rc463_seed_family='459820001..459820120';x.instrumentation_contract='pre-safety raw snapshot captured before applyPlayerQualitySafetyGate mutates any row; no policy/RNG/choice mutation';x.production_mutation=false;const dst=`simulation_2026/RC463_FULL_SAFETY_PRESAFETY_SHARD_${shard}_2026.json`;fs.renameSync(src,dst);fs.writeFileSync(dst,JSON.stringify(x));console.log(JSON.stringify({status:'PASS',shard,start,end:start+9,output:dst},null,2))}}finally{fs.writeFileSync(POLICY,policy0)}if(status!==0)process.exit(status);
