'use strict';
/* Research-only v5 challenger.
   Retains v3 narrow late WR-saturation near-tie behavior, but replaces the fixed
   post-100 repeat-QB/TE penalty with an explicit marginal-value hurdle versus the
   best legal RB/WR at every state after QB1/TE1. Exceptional slides remain eligible.
   No player-name rule, hard quota, app/runtime or production mutation. */
const fs=require('fs'),crypto=require('crypto'),cp=require('child_process'),path=require('path');
const SRC='research/rc459_meta_safe_qbte_no_safety_resurrection_shard_2026.js';
const EXPECT='8827e0c83b4a55e5a38b5033d88d1effc8e8622b';
function gitBlob(s){const b=Buffer.from(s);return crypto.createHash('sha1').update(Buffer.from(`blob ${b.length}\0`)).update(b).digest('hex')}
const src0=fs.readFileSync(SRC,'utf8');if(gitBlob(src0)!==EXPECT)throw Error('BASE_SHARD_DRIFT '+gitBlob(src0));
let s=src0;
for(const [a,b] of [["shard<0||shard>5","shard<0||shard>11"],["PITTI_SHARD 0..5 required","PITTI_SHARD 0..11 required"],["const start=459710001+10*shard;","const start=459820001+10*shard;"],["RC459_META_SAFE_QBTE_NO_SAFETY_RESURRECTION_SHARD_${shard}_2026.json","RC463_ROSTER_CHAMPIONSHIP_V5_MARGINAL_SHARD_${shard}_2026.json"]]){if(!s.includes(a))throw Error('V5_SCALE_ANCHOR_DRIFT '+a);s=s.replace(a,b)}
const insertAnchor=`full=full.replace(feasibilityAnchor,"H.ok(c.QB>=1&&c.RB>=1&&c.WR>=2,'draft-end user-policy feasibility');");`;
if(s.split(insertAnchor).length!==2)throw Error('V5_INSERT_ANCHOR_DRIFT');
const inject=`${insertAnchor}\nconst decisionAnchor="C.normalizeCoachScores(scored);scored.sort((a,b)=>b.score-a.score||b.rawScore-a.rawScore||a.r.rank-b.r.rank);";\nif(full.split(decisionAnchor).length!==2)throw Error('V5_DECISION_PRIORITY_ANCHOR_DRIFT');\nconst decisionPatch=\`C.normalizeCoachScores(scored);for(const x of scored)x.__decisionPriorityV5=Number(x.score||0);const __counts=state.counts||{};const __valid=scored.filter(x=>!x.hardExcluded&&!x.recommendationBlocked&&Number.isFinite(x.rawScore));const __bestSkill=__valid.filter(x=>['RB','WR'].includes(String(x.p.pos||''))).sort((a,b)=>b.rawScore-a.rawScore||a.r.rank-b.r.rank)[0];if(__bestSkill){for(const x of __valid){const pos=String(x.p.pos||''),n=Number(__counts[pos]||0);if(!((pos==='QB'||pos==='TE')&&n>=1))continue;const panel=Number(x.r.rank),slide=Number.isFinite(x.a)?pn-Number(x.a):0;const exceptional=pos==='QB'?(panel<=45&&slide>=35):(panel<=35&&slide>=30);if(!exceptional&&Number(x.rawScore)<Number(__bestSkill.rawScore)+1.0)x.__decisionPriorityV5=Math.min(x.__decisionPriorityV5,__bestSkill.__decisionPriorityV5-0.01);}}if(pn>=120&&Number(__counts.WR||0)>=6){const bestWR=__valid.filter(x=>String(x.p.pos||'')==='WR').sort((a,b)=>b.rawScore-a.rawScore||a.r.rank-b.r.rank)[0];const bestRB=__valid.filter(x=>String(x.p.pos||'')==='RB').sort((a,b)=>b.rawScore-a.rawScore||a.r.rank-b.r.rank)[0];if(bestWR&&bestRB){const gap=Number(bestWR.rawScore)-Number(bestRB.rawScore);const rbCount=Number(__counts.RB||0);if(gap>=0&&gap<=1.0&&rbCount<7)bestRB.__decisionPriorityV5=Math.max(bestRB.__decisionPriorityV5,bestWR.__decisionPriorityV5+0.01);}}scored.sort((a,b)=>b.__decisionPriorityV5-a.__decisionPriorityV5||b.score-a.score||b.rawScore-a.rawScore||a.r.rank-b.r.rank);\`;\nfull=full.replace(decisionAnchor,decisionPatch);`;
s=s.replace(insertAnchor,inject);
const marker="x.production_mutation=false;";if(s.split(marker).length!==2)throw Error('V5_OUTPUT_MARKER_ANCHOR_DRIFT');s=s.replace(marker,"x.production_mutation=false;x.rc463_roster_championship_v5_marginal=true;x.rc463_ab_seed_family='459820001..459820120';x.qbte_marginal_hurdle='repeat QB/TE must exceed best legal RB/WR rawScore by >=1.0 unless existing exceptional-slide condition';x.late_wr_neartie='v3 late WR>=6, pn>=120, WR-RB raw gap <=1.0, RB<7';");
const shard=String(process.env.PITTI_SHARD??'');const tmp=path.join('/tmp',`pitti_rc463_roster_championship_v5_${shard}.js`);fs.writeFileSync(tmp,s);const r=cp.spawnSync(process.execPath,[tmp],{stdio:'inherit',env:process.env});if(r.error)throw r.error;process.exit(r.status??2);
