'use strict';
/* Exact frozen natural pick92 causal A/B: production full PlayerQualitySafetyGate
   versus the minimal repeat-QB/TE safety-resurrection guard. No v5 marginal hurdle.
   Research only; raw scores are recomputed from the frozen 91-pick state. */
const fs=require('fs'),crypto=require('crypto');
const CORE='research/rc459_decision_counterfactual_screen_2026.js',FIX='research/fixtures/rc463_natural_pick92_20260824.json';
const core=fs.readFileSync(CORE,'utf8'),fixture=JSON.parse(fs.readFileSync(FIX,'utf8'));
function ok(x,m){if(!x)throw Error('RC463_PICK92_SAFETY_AB: '+m)}
const main=core.indexOf('(async()=>');ok(main>0,'core main boundary');const H=new Function('require','fetch','structuredClone',core.slice(0,main)+'\nreturn {getFixture,apiFrom,init};')(require,fetch,structuredClone);
function buildState(api,players,liveMeta){const s=H.init(api,players,463092002),norm=api.C.__norm,byName=new Map();for(const p of Object.values(players)){const k=norm(p.name);if(!byName.has(k))byName.set(k,[]);byName.get(k).push(p)}for(const q of fixture.picks){const md=liveMeta[String(q.player_id)]||{},liveName=md.full_name||[md.first_name,md.last_name].filter(Boolean).join(' ')||q.player_name;let m=byName.get(norm(liveName))||byName.get(norm(q.player_name))||[];ok(m.length<=1,'ambiguous '+q.pick_no);let p;if(m.length===1){p=m[0];ok(s.available.has(p.key),'unavailable '+q.pick_no);s.available.delete(p.key)}else{const pos=String(md.position||md.fantasy_positions?.[0]||'').toUpperCase();ok(['QB','RB','WR','TE'].includes(pos),'missing pos '+q.pick_no);p={key:`__frozen_${q.player_id}`,id:`__frozen_${q.player_id}`,name:liveName,pos,team:String(md.team||'FA'),panel:9999,adp:9999,searchRank:9999};s.pm[p.key]=api.pmeta(p)}s.rosters[+q.draft_slot].push(p);api.addPick(s.picks,s.pm,+q.pick_no,+q.draft_slot,p)}s.nextPn=92;return s}
function baseRows(api,players,s){const C=api.C,pn=92,next=109,mine=s.picks.filter(p=>+p.draft_slot===api.USER_SLOT),state=C.rosterState(mine,s.pm,pn),ranked=[...s.available].map(k=>players[k]).filter(Boolean).map(p=>({p,r:C.rankFor(p.name,p.pos)})).filter(x=>x.r).sort((a,b)=>a.r.rank-b.r.rank||(a.p.searchRank||9999)-(b.p.searchRank||9999)).map(x=>x.p);let scored=ranked.map(p=>({p,...C.scoreCandidate(p,pn,next,state,ranked,'progressive')})).filter(x=>x.r),rv=C.simulateReturnV2({current:pn,next,picks:s.picks,players:s.pm,teams:10,map:api.MAP,rankedAvailable:ranked,mode:'mock',userSlot:api.USER_SLOT},'baseline',900);for(const x of scored){const q=rv?.players?.[C.__norm(x.p.name)];if(q){x.ret=q.ret;x.returnConfidence=q.confidence;x.topRisk=q.topRisk}C.applyResolvedReturnScore(x,pn,'progressive')}const boardTop=scored.slice().sort((x,y)=>x.r.rank-y.r.rank).slice(0,12).filter(x=>x.ret!=null),rets=boardTop.map(x=>x.ret).sort((a,b)=>a-b),med=rets.length?rets[Math.floor(rets.length/2)]:null;if(med!=null)for(const x of scored)if(x.ret!=null)x.rawScore+=C.__clamp((med-x.ret)*6,-3,3);return{state,scored,med}}
function cloneRows(rows){return rows.map(x=>({...x,reasons:[...(x.reasons||[])],valueSafety:x.valueSafety?{...x.valueSafety}:x.valueSafety}))}
function finish(api,rows){api.C.normalizeCoachScores(rows);rows.sort((a,b)=>b.score-a.score||b.rawScore-a.rawScore||a.r.rank-b.r.rank);return rows}
function row(x){return{name:x.p.name,pos:x.p.pos,panel:+x.r.rank,adp:Number.isFinite(x.a)?+x.a:null,raw:+x.rawScore.toFixed(6),score:x.score,valueSafety:x.valueSafety||null}}
(async()=>{const meta=await H.getFixture(),api=H.apiFrom(meta);await api.loadMeta();const players=api.buildPlayers();api.initRepl(players);const s=buildState(api,players,meta),b=baseRows(api,players,s),C=api.C,pn=92;
 const full=cloneRows(b.scored);const fullGate=C.applyPlayerQualitySafetyGate(full,pn);finish(api,full);
 const guard=cloneRows(b.scored),valid=guard.filter(x=>x?.r&&Number.isFinite(x.r.rank)&&Number.isFinite(x.rawScore)&&!x.hardExcluded&&!x.recommendationBlocked),natural=valid.slice().sort((a,b)=>b.rawScore-a.rawScore||a.r.rank-b.r.rank)[0],guardRows=guard.filter(x=>{const pos=x.p.pos,n=Number(b.state.counts?.[pos]||0);if((pos==='QB'||pos==='TE')&&n>=1){const elite=pos==='QB'?(x.r.rank<=45&&Number.isFinite(x.a)&&pn-x.a>=35):(x.r.rank<=35&&Number.isFinite(x.a)&&pn-x.a>=30);return x===natural||elite}return true});const guardGate=C.applyPlayerQualitySafetyGate(guardRows,pn);finish(api,guard);
 const fTL=full.find(x=>x.p.name==='Trevor Lawrence'),fC=full.find(x=>x.p.name==='Blake Corum'),gTL=guard.find(x=>x.p.name==='Trevor Lawrence'),gC=guard.find(x=>x.p.name==='Blake Corum');ok(fTL&&fC&&gTL&&gC,'control candidates');ok(full[0].p.name==='Trevor Lawrence','full safety did not reproduce Trevor leader: '+full[0].p.name);ok(guard[0].p.name==='Blake Corum','guard did not produce Corum leader: '+guard[0].p.name);ok(natural.p.name==='Blake Corum','natural raw leader unexpected '+natural.p.name);ok(fTL.valueSafety?.promoted===true,'Trevor not marked safety-promoted');
 const out={schema:1,status:'PASS',research_only:true,production_mutation:false,fixture:{draft_id:fixture.source_draft_id,pick:92,modelVersion:fixture.modelVersion,picks:fixture.picks.length},user_counts:b.state.counts,median_return:b.med,natural_pre_safety_leader:row(natural),production_full_safety:{gate:fullGate,leader:row(full[0]),trevor:row(fTL),corum:row(fC)},minimal_repeat_qbte_safety_guard:{gate:guardGate,leader:row(guard[0]),trevor:row(gTL),corum:row(gC)},checks:{same_recomputed_pre_safety_rows:true,full_safety_reproduces_trevor_qb2_leader:true,trevor_is_safety_promoted:true,minimal_guard_restores_corum_raw_leader:true,no_hard_qb2_ban:true},interpretation:'Exact frozen natural pick92 causal A/B isolates PlayerQualitySafety safety-only resurrection as the mechanism: production full safety promotes Trevor Lawrence QB2 above natural raw leader Blake Corum; the minimal repeat-QB/TE safety guard restores Corum without removing QB2 from the normal board.',promotion_authorized:false};fs.mkdirSync('diagnostics_2026',{recursive:true});fs.writeFileSync('diagnostics_2026/RC463_NATURAL_PICK92_SAFETY_AB_20260825.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))})().catch(e=>{console.error(e.stack||e);process.exit(2)});
